use crate::{config::DATABASE_FILE, protocol::*};
use anyhow::{Result, anyhow, bail};
use serde_json::Value;
use sqlx::{
    ConnectOptions, Row, SqlitePool,
    sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous},
};
use std::{
    collections::HashSet,
    path::{Path, PathBuf},
    str::FromStr,
};
use time::OffsetDateTime;

#[derive(Clone)]
pub struct ClientStore {
    pool: SqlitePool,
}
#[derive(Debug, Clone)]
pub struct ProjectRecord {
    pub summary: ProjectSummary,
    pub canonical_path: PathBuf,
    pub defaults: Value,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProjectRemoval {
    pub thread_count: i64,
    pub already_removed: bool,
}
#[derive(Debug, Clone)]
pub struct InboxRecord {
    pub queue_epoch: String,
    pub server_sequence: i64,
    pub target_key: String,
    pub priority: i64,
    pub command: DeviceCommand,
    pub status: String,
    pub result: Option<Value>,
    pub error_code: Option<String>,
    pub error_message: Option<String>,
}

impl ClientStore {
    pub async fn open(root: &Path) -> Result<Self> {
        let path = root.join(DATABASE_FILE);
        let url = format!("sqlite://{}", path.to_string_lossy());
        let options = SqliteConnectOptions::from_str(&url)?
            .create_if_missing(true)
            .journal_mode(SqliteJournalMode::Wal)
            .synchronous(SqliteSynchronous::Full)
            .foreign_keys(true)
            .busy_timeout(std::time::Duration::from_secs(15))
            .disable_statement_logging();
        let pool = SqlitePoolOptions::new()
            .max_connections(4)
            .connect_with(options)
            .await?;
        sqlx::migrate!("./migrations").run(&pool).await?;
        crate::config::private_file(&path)?;
        for suffix in ["-wal", "-shm"] {
            let sidecar = PathBuf::from(format!("{}{suffix}", path.display()));
            if sidecar.exists() {
                crate::config::private_file(&sidecar)?;
            }
        }
        Ok(Self { pool })
    }
    pub async fn ready(&self) -> Result<()> {
        sqlx::query("SELECT 1").execute(&self.pool).await?;
        Ok(())
    }
    pub async fn maintenance(&self) -> Result<()> {
        sqlx::query("DELETE FROM directory_refs WHERE expires_at<=?")
            .bind(OffsetDateTime::now_utc().unix_timestamp())
            .execute(&self.pool)
            .await?;
        sqlx::query("PRAGMA wal_checkpoint(PASSIVE)")
            .execute(&self.pool)
            .await?;
        // Keep enough short-term control events for browser reconnects without
        // turning the replay journal into a second long-term history store.
        sqlx::query(
            "DELETE FROM browser_event_journal WHERE cursor < COALESCE((SELECT MAX(cursor)-10000 FROM browser_event_journal), 0)",
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }
    pub async fn backup(&self, destination: &Path) -> Result<()> {
        if destination.exists() {
            anyhow::bail!(
                "backup destination already exists: {}",
                destination.display()
            );
        }
        let escaped = destination.to_string_lossy().replace('\'', "''");
        // `destination` is generated by the CLI inside the private data directory;
        // single quotes are escaped above before opting this dynamic SQLite
        // statement out of SQLx's static SQL check.
        sqlx::query(sqlx::AssertSqlSafe(format!("VACUUM INTO '{escaped}'")))
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn recover_process_state(&self) -> Result<Vec<String>> {
        let stamp = now();
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        // Preserve every conversation that may still be executing. `unknown`
        // with an in-progress turn covers clients upgraded from the previous
        // restart behavior, which changed only the thread status.
        let recovery_threads = sqlx::query_scalar(
            "SELECT t.id FROM threads t WHERE t.status IN ('active','recovering') OR (t.status='unknown' AND EXISTS(SELECT 1 FROM turns r WHERE r.thread_id=t.id AND r.status IN ('active','running','inProgress'))) ORDER BY t.id",
        )
        .fetch_all(&mut *tx)
        .await?;
        sqlx::query(
            "UPDATE pending_app_requests SET status='unknown',decided_at=?,error_message='client_restarted_before_decision' WHERE status IN ('pending','responding')",
        )
        .bind(&stamp)
        .execute(&mut *tx)
        .await?;
        sqlx::query(
            "UPDATE threads SET status='recovering',updated_at=? WHERE status IN ('active','recovering') OR (status='unknown' AND EXISTS(SELECT 1 FROM turns r WHERE r.thread_id=threads.id AND r.status IN ('active','running','inProgress')))",
        )
            .bind(&stamp)
            .execute(&mut *tx)
            .await?;
        // Archive expresses an idempotent desired state, so it is safe to run again after
        // a process restart. Other applying commands retain the conservative unknown state.
        sqlx::query("UPDATE command_inbox SET status='accepted',started_at=NULL,completed_at=NULL,error_code=NULL,error_message=NULL WHERE status='applying' AND json_extract(payload,'$.command.kind')='thread_archive'")
            .execute(&self.pool)
            .await?;
        sqlx::query("UPDATE turns SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE status IN ('active','running','inProgress')")
            .bind(&stamp)
            .execute(&self.pool)
            .await?;
        sqlx::query("UPDATE items SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE status IN ('active','running','inProgress')")
            .bind(&stamp)
            .execute(&self.pool)
            .await?;
        sqlx::query("UPDATE command_inbox SET status='unknown',completed_at=?,error_code='execution_state_unknown_after_restart',error_message='客户端重启，无法确认命令是否已经执行' WHERE status='applying'")
            .bind(&stamp)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(recovery_threads)
    }
    pub async fn pending_approval_count(&self) -> Result<i64> {
        Ok(
            sqlx::query_scalar("SELECT COUNT(*) FROM pending_app_requests WHERE status='pending'")
                .fetch_one(&self.pool)
                .await?,
        )
    }
    pub async fn state_get(&self, key: &str) -> Result<Option<String>> {
        Ok(
            sqlx::query_scalar("SELECT value FROM runtime_state WHERE key=?")
                .bind(key)
                .fetch_optional(&self.pool)
                .await?,
        )
    }
    pub async fn state_set(&self, key: &str, value: &str) -> Result<()> {
        sqlx::query("INSERT INTO runtime_state(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(key).bind(value).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn next_history_revision(&self, thread_id: &str) -> Result<i64> {
        let key = format!("history_revision:{thread_id}");
        let revision: String = sqlx::query_scalar("INSERT INTO runtime_state(key,value,updated_at) VALUES(?,'1',?) ON CONFLICT(key) DO UPDATE SET value=CAST(runtime_state.value AS INTEGER)+1,updated_at=excluded.updated_at RETURNING value")
            .bind(key).bind(now()).fetch_one(&self.pool).await?;
        Ok(revision.parse()?)
    }
    pub async fn active_command_queue_epoch(&self) -> Result<Option<String>> {
        self.state_get("active_command_queue_epoch").await
    }
    pub async fn last_server_sequence(&self, queue_epoch: Option<&str>) -> Result<i64> {
        let key = queue_epoch
            .map(|epoch| format!("last_server_sequence:{epoch}"))
            .unwrap_or_else(|| "last_server_sequence".into());
        Ok(self
            .state_get(&key)
            .await?
            .and_then(|v| v.parse().ok())
            .unwrap_or(0))
    }

    pub async fn list_projects(&self, device_id: &str) -> Result<Vec<ProjectSummary>> {
        let rows=sqlx::query("SELECT p.*,(SELECT COUNT(*) FROM threads t WHERE t.project_id=p.id AND t.archived=0) thread_count FROM projects p WHERE status='active' ORDER BY julianday(updated_at) DESC,id DESC").fetch_all(&self.pool).await?;
        Ok(rows
            .into_iter()
            .map(|r| project_summary(&r, device_id))
            .collect())
    }
    pub async fn project(&self, id: &str, device_id: &str) -> Result<Option<ProjectRecord>> {
        let row=sqlx::query("SELECT p.*,(SELECT COUNT(*) FROM threads t WHERE t.project_id=p.id AND t.archived=0) thread_count FROM projects p WHERE id=? AND status='active'").bind(id).fetch_optional(&self.pool).await?;
        Ok(row.map(|r| ProjectRecord {
            canonical_path: PathBuf::from(r.get::<String, _>("canonical_path")),
            defaults: serde_json::from_str(&r.get::<String, _>("defaults_json"))
                .unwrap_or(Value::Object(Default::default())),
            summary: project_summary(&r, device_id),
        }))
    }
    pub async fn project_by_path(&self, path: &Path) -> Result<Option<String>> {
        Ok(
            sqlx::query_scalar(
                "SELECT id FROM projects WHERE canonical_path=? AND status='active'",
            )
            .bind(path.to_string_lossy().as_ref())
            .fetch_optional(&self.pool)
            .await?,
        )
    }
    pub async fn ensure_unassigned_project(&self, device_id: &str) -> Result<String> {
        if let Some(id) =
            sqlx::query_scalar("SELECT id FROM projects WHERE kind='system_unassigned' LIMIT 1")
                .fetch_optional(&self.pool)
                .await?
        {
            return Ok(id);
        }
        let id = new_id("prj_unassigned");
        let stamp = now();
        let path = format!("nuntius://system-unassigned/{device_id}");
        sqlx::query("INSERT INTO projects(id,kind,display_name,canonical_path,status,defaults_json,created_at,updated_at) VALUES(?,'system_unassigned','未归类',?,'system_unassigned','{}',?,?)")
            .bind(&id).bind(path).bind(&stamp).bind(&stamp).execute(&self.pool).await?;
        Ok(id)
    }
    pub async fn create_project(
        &self,
        id: &str,
        name: &str,
        path: &Path,
        defaults: &Value,
    ) -> Result<()> {
        let stamp = now();
        let canonical_path = path.to_string_lossy();
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("DELETE FROM removed_app_threads WHERE canonical_path=?")
            .bind(canonical_path.as_ref())
            .execute(&mut *tx)
            .await?;
        sqlx::query("DELETE FROM removed_project_paths WHERE canonical_path=?")
            .bind(canonical_path.as_ref())
            .execute(&mut *tx)
            .await?;
        sqlx::query("INSERT INTO projects(id,display_name,canonical_path,defaults_json,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(id).bind(name).bind(canonical_path.as_ref()).bind(serde_json::to_string(defaults)?).bind(&stamp).bind(&stamp).execute(&mut *tx).await?;
        tx.commit().await?;
        Ok(())
    }

    pub async fn remove_project(&self, id: &str) -> Result<Option<ProjectRemoval>> {
        let stamp = now();
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let project = sqlx::query("SELECT kind,canonical_path FROM projects WHERE id=?")
            .bind(id)
            .fetch_optional(&mut *tx)
            .await?;
        let Some(project) = project else {
            let already_removed: Option<i64> =
                sqlx::query_scalar("SELECT 1 FROM removed_project_paths WHERE project_id=?")
                    .bind(id)
                    .fetch_optional(&mut *tx)
                    .await?;
            tx.commit().await?;
            return Ok(already_removed.map(|_| ProjectRemoval {
                thread_count: 0,
                already_removed: true,
            }));
        };
        if project.get::<String, _>("kind") != "workspace" {
            bail!("系统项目不能删除");
        }
        let active_threads: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM threads WHERE project_id=? AND status IN ('active','recovering')",
        )
        .bind(id)
        .fetch_one(&mut *tx)
        .await?;
        if active_threads > 0 {
            bail!("项目中仍有运行中的会话，请先中断或等待会话结束");
        }
        let canonical_path: String = project.get("canonical_path");
        let threads =
            sqlx::query("SELECT id,provider,app_server_thread_id FROM threads WHERE project_id=?")
                .bind(id)
                .fetch_all(&mut *tx)
                .await?;
        let thread_count = threads.len() as i64;

        sqlx::query("INSERT INTO removed_project_paths(canonical_path,project_id,removed_at) VALUES(?,?,?) ON CONFLICT(canonical_path) DO UPDATE SET project_id=excluded.project_id,removed_at=excluded.removed_at")
            .bind(&canonical_path)
            .bind(id)
            .bind(&stamp)
            .execute(&mut *tx)
            .await?;
        for thread in &threads {
            let thread_id: String = thread.get("id");
            let provider: String = thread.get("provider");
            if let Some(app_thread_id) = thread.get::<Option<String>, _>("app_server_thread_id") {
                sqlx::query("INSERT INTO removed_app_threads(app_server_thread_id,canonical_path,removed_at,provider) VALUES(?,?,?,?) ON CONFLICT(app_server_thread_id) DO UPDATE SET canonical_path=excluded.canonical_path,removed_at=excluded.removed_at,provider=excluded.provider")
                    .bind(&app_thread_id)
                    .bind(&canonical_path)
                    .bind(&stamp)
                    .bind(&provider)
                    .execute(&mut *tx)
                    .await?;
                sqlx::query("DELETE FROM runtime_state WHERE key=?")
                    .bind(format!(
                        "provider_thread_fingerprint:{provider}:{app_thread_id}"
                    ))
                    .execute(&mut *tx)
                    .await?;
            }
            sqlx::query("DELETE FROM history_outbox WHERE thread_id=?")
                .bind(&thread_id)
                .execute(&mut *tx)
                .await?;
            sqlx::query("DELETE FROM runtime_state WHERE key IN (?,?)")
                .bind(format!("history_hash:{thread_id}"))
                .bind(format!("history_revision:{thread_id}"))
                .execute(&mut *tx)
                .await?;
        }
        sqlx::query("DELETE FROM event_outbox WHERE json_extract(payload,'$.projectId')=?")
            .bind(id)
            .execute(&mut *tx)
            .await?;
        sqlx::query("DELETE FROM threads WHERE project_id=?")
            .bind(id)
            .execute(&mut *tx)
            .await?;
        sqlx::query("DELETE FROM projects WHERE id=?")
            .bind(id)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(Some(ProjectRemoval {
            thread_count,
            already_removed: false,
        }))
    }

    pub async fn project_path_removed(&self, path: &Path) -> Result<bool> {
        let removed: Option<i64> =
            sqlx::query_scalar("SELECT 1 FROM removed_project_paths WHERE canonical_path=?")
                .bind(path.to_string_lossy().as_ref())
                .fetch_optional(&self.pool)
                .await?;
        Ok(removed.is_some())
    }

    pub async fn app_thread_removed(&self, app_thread_id: &str) -> Result<bool> {
        self.provider_thread_removed(AgentProvider::Codex, app_thread_id)
            .await
    }

    pub async fn provider_thread_removed(
        &self,
        provider: AgentProvider,
        app_thread_id: &str,
    ) -> Result<bool> {
        let removed: Option<i64> = sqlx::query_scalar(
            "SELECT 1 FROM removed_app_threads WHERE provider=? AND app_server_thread_id=?",
        )
        .bind(provider.as_str())
        .bind(app_thread_id)
        .fetch_optional(&self.pool)
        .await?;
        Ok(removed.is_some())
    }

    pub async fn list_threads(
        &self,
        device_id: &str,
        project_id: Option<&str>,
    ) -> Result<Vec<ThreadSummary>> {
        self.list_threads_page(device_id, project_id, -1, 0).await
    }
    pub async fn list_threads_page(
        &self,
        device_id: &str,
        project_id: Option<&str>,
        limit: i64,
        offset: i64,
    ) -> Result<Vec<ThreadSummary>> {
        let rows = if let Some(project) = project_id {
            sqlx::query("SELECT * FROM threads WHERE project_id=? AND archived=0 ORDER BY julianday(COALESCE(last_activity_at,created_at)) DESC,id DESC LIMIT ? OFFSET ?").bind(project).bind(limit).bind(offset).fetch_all(&self.pool).await?
        } else {
            sqlx::query("SELECT * FROM threads WHERE archived=0 ORDER BY julianday(COALESCE(last_activity_at,created_at)) DESC,id DESC LIMIT ? OFFSET ?").bind(limit).bind(offset).fetch_all(&self.pool).await?
        };
        Ok(rows
            .into_iter()
            .map(|r| thread_summary(&r, device_id))
            .collect())
    }
    pub async fn thread(&self, id: &str, device_id: &str) -> Result<Option<ThreadSummary>> {
        Ok(sqlx::query("SELECT * FROM threads WHERE id=?")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?
            .map(|r| thread_summary(&r, device_id)))
    }
    pub async fn controllable_thread(
        &self,
        id: &str,
        device_id: &str,
    ) -> Result<Option<ThreadSummary>> {
        Ok(sqlx::query("SELECT t.* FROM threads t JOIN projects p ON p.id=t.project_id WHERE t.id=? AND t.archived=0 AND p.kind='workspace' AND p.status='active'")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?
            .map(|row| thread_summary(&row, device_id)))
    }
    pub async fn create_thread(
        &self,
        id: &str,
        project_id: &str,
        app_id: &str,
        title: &str,
        app_server_options: &Value,
    ) -> Result<()> {
        self.create_provider_thread(
            id,
            project_id,
            AgentProvider::Codex,
            app_id,
            title,
            ConversationAccessMode::Full,
            app_server_options,
        )
        .await
    }
    pub async fn create_provider_thread(
        &self,
        id: &str,
        project_id: &str,
        provider: AgentProvider,
        app_id: &str,
        title: &str,
        access_mode: ConversationAccessMode,
        app_server_options: &Value,
    ) -> Result<()> {
        let stamp = now();
        sqlx::query("INSERT INTO threads(id,project_id,provider,app_server_thread_id,title,access_mode,app_server_options,last_activity_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id).bind(project_id).bind(provider.as_str()).bind(app_id).bind(title).bind(access_mode.as_str()).bind(serde_json::to_string(app_server_options)?).bind(&stamp).bind(&stamp).bind(&stamp).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn thread_has_turns(&self, id: &str) -> Result<bool> {
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM turns WHERE thread_id=?")
            .bind(id)
            .fetch_one(&self.pool)
            .await?;
        Ok(count > 0)
    }
    pub async fn app_server_options(&self, id: &str) -> Result<Value> {
        let encoded: String =
            sqlx::query_scalar("SELECT app_server_options FROM threads WHERE id=?")
                .bind(id)
                .fetch_one(&self.pool)
                .await?;
        Ok(serde_json::from_str(&encoded).unwrap_or_else(|_| Value::Object(Default::default())))
    }
    pub async fn thread_access_mode(&self, id: &str) -> Result<ConversationAccessMode> {
        let mode: String = sqlx::query_scalar("SELECT access_mode FROM threads WHERE id=?")
            .bind(id)
            .fetch_one(&self.pool)
            .await?;
        Ok(if mode == "ask" {
            ConversationAccessMode::Ask
        } else {
            ConversationAccessMode::Full
        })
    }
    pub async fn rebind_app_server_thread(&self, id: &str, app_id: &str) -> Result<()> {
        sqlx::query(
            "UPDATE threads SET app_server_thread_id=?,status='idle',updated_at=? WHERE id=?",
        )
        .bind(app_id)
        .bind(now())
        .bind(id)
        .execute(&self.pool)
        .await?;
        Ok(())
    }
    pub async fn set_thread_archived(&self, id: &str, archived: bool) -> Result<()> {
        sqlx::query("UPDATE threads SET archived=?,updated_at=? WHERE id=?")
            .bind(archived)
            .bind(now())
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    /// App-server turn id of the thread's currently active turn, if any.
    pub async fn active_app_turn_id(&self, thread_id: &str) -> Result<Option<String>> {
        Ok(sqlx::query_scalar(
            "SELECT app_server_turn_id FROM turns WHERE thread_id=? AND status IN ('active','running','inProgress') AND app_server_turn_id IS NOT NULL ORDER BY ordinal DESC LIMIT 1",
        )
        .bind(thread_id)
        .fetch_optional(&self.pool)
        .await?)
    }
    pub async fn touch_thread(&self, id: &str, status: &str) -> Result<()> {
        sqlx::query("UPDATE threads SET status=?,last_activity_at=?,updated_at=? WHERE id=?")
            .bind(status)
            .bind(now())
            .bind(now())
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn set_thread_status(&self, id: &str, status: &str) -> Result<()> {
        sqlx::query("UPDATE threads SET status=?,updated_at=? WHERE id=?")
            .bind(status)
            .bind(now())
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn local_thread_id(&self, app_thread_id: &str) -> Result<Option<String>> {
        self.local_provider_thread_id(AgentProvider::Codex, app_thread_id)
            .await
    }
    pub async fn local_provider_thread_id(
        &self,
        provider: AgentProvider,
        app_thread_id: &str,
    ) -> Result<Option<String>> {
        Ok(
            sqlx::query_scalar(
                "SELECT id FROM threads WHERE provider=? AND app_server_thread_id=?",
            )
            .bind(provider.as_str())
            .bind(app_thread_id)
            .fetch_optional(&self.pool)
            .await?,
        )
    }
    pub async fn record_user_turn(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
        text: &str,
        attachments: &[AttachmentView],
    ) -> Result<String> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let stamp = now();
        let mut existing = if let Some(app_turn_id) = app_turn_id {
            sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id=?",
            )
            .bind(thread_id)
            .bind(app_turn_id)
            .fetch_optional(&mut *tx)
            .await?
        } else {
            None
        };
        if existing.is_none() && app_turn_id.is_some() {
            existing = sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id IS NULL AND status IN ('active','running','inProgress') ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_optional(&mut *tx)
            .await?;
        }
        let turn_id = existing.clone().unwrap_or_else(|| new_id("trn"));
        sqlx::query("UPDATE turns SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE thread_id=? AND id<>? AND status IN ('active','running','inProgress')")
            .bind(&stamp).bind(thread_id).bind(&turn_id).execute(&mut *tx).await?;
        if existing.is_some() {
            sqlx::query("UPDATE turns SET app_server_turn_id=COALESCE(app_server_turn_id,?),status='inProgress',started_at=COALESCE(started_at,?),completed_at=NULL WHERE id=?")
                .bind(app_turn_id).bind(&stamp).bind(&turn_id).execute(&mut *tx).await?;
        } else {
            let ordinal: i64 = sqlx::query_scalar(
                "SELECT COALESCE(MAX(ordinal),0)+1 FROM turns WHERE thread_id=?",
            )
            .bind(thread_id)
            .fetch_one(&mut *tx)
            .await?;
            sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,?,?,'inProgress',?)")
                .bind(&turn_id).bind(thread_id).bind(app_turn_id).bind(ordinal).bind(&stamp)
                .execute(&mut *tx).await?;
        }
        let item_id = if let Some(item_id) = sqlx::query_scalar::<_, String>(
            "SELECT id FROM items WHERE turn_id=? AND kind='user_message' AND content_text=? LIMIT 1",
        )
        .bind(&turn_id)
        .bind(text)
        .fetch_optional(&mut *tx)
        .await?
        {
            item_id
        } else {
            let item_id = new_id("itm");
            let item_ordinal: i64 = sqlx::query_scalar(
                "SELECT COALESCE(MAX(ordinal),0)+1 FROM items WHERE turn_id=?",
            )
            .bind(&turn_id)
            .fetch_one(&mut *tx)
            .await?;
            sqlx::query("INSERT INTO items(id,turn_id,ordinal,kind,status,content_text,occurred_at,completed_at) VALUES(?,?,?,'user_message','completed',?,?,?)")
                .bind(&item_id).bind(&turn_id).bind(item_ordinal).bind(text).bind(&stamp).bind(&stamp)
                .execute(&mut *tx).await?;
            item_id
        };
        for (index, attachment) in attachments.iter().enumerate() {
            sqlx::query(
                "INSERT INTO item_attachments(item_id,attachment_id,ordinal) VALUES(?,?,?)",
            )
            .bind(&item_id)
            .bind(&attachment.id)
            .bind(index as i64 + 1)
            .execute(&mut *tx)
            .await?;
        }
        sqlx::query(
            "UPDATE threads SET status='active',last_activity_at=?,updated_at=? WHERE id=?",
        )
        .bind(&stamp)
        .bind(&stamp)
        .bind(thread_id)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(turn_id)
    }

    pub async fn mark_app_turn_started(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
    ) -> Result<String> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let stamp = now();
        let mut existing = if let Some(app_turn_id) = app_turn_id {
            sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id=?",
            )
            .bind(thread_id)
            .bind(app_turn_id)
            .fetch_optional(&mut *tx)
            .await?
        } else {
            sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND status IN ('active','running','inProgress') ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_optional(&mut *tx)
            .await?
        };
        if existing.is_none() && app_turn_id.is_some() {
            existing = sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id IS NULL AND status IN ('active','running','inProgress') ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_optional(&mut *tx)
            .await?;
        }
        let turn_id = existing.clone().unwrap_or_else(|| new_id("trn"));
        sqlx::query("UPDATE turns SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE thread_id=? AND id<>? AND status IN ('active','running','inProgress')")
            .bind(&stamp).bind(thread_id).bind(&turn_id).execute(&mut *tx).await?;
        if existing.is_some() {
            sqlx::query("UPDATE turns SET app_server_turn_id=COALESCE(app_server_turn_id,?),status='inProgress',started_at=COALESCE(started_at,?),completed_at=NULL WHERE id=?")
                .bind(app_turn_id).bind(&stamp).bind(&turn_id).execute(&mut *tx).await?;
        } else {
            let ordinal: i64 = sqlx::query_scalar(
                "SELECT COALESCE(MAX(ordinal),0)+1 FROM turns WHERE thread_id=?",
            )
            .bind(thread_id)
            .fetch_one(&mut *tx)
            .await?;
            sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,?,?,'inProgress',?)")
                .bind(&turn_id).bind(thread_id).bind(app_turn_id).bind(ordinal).bind(&stamp)
                .execute(&mut *tx).await?;
        }
        sqlx::query(
            "UPDATE threads SET status='active',last_activity_at=?,updated_at=? WHERE id=?",
        )
        .bind(&stamp)
        .bind(&stamp)
        .bind(thread_id)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(turn_id)
    }

    pub async fn upsert_attachment(
        &self,
        thread_id: &str,
        attachment: &AttachmentRef,
        local_path: &Path,
    ) -> Result<AttachmentView> {
        sqlx::query("INSERT INTO attachments(id,thread_id,original_name,mime_type,extension,byte_size,sha256,width,height,local_path,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET thread_id=excluded.thread_id,original_name=excluded.original_name,mime_type=excluded.mime_type,extension=excluded.extension,byte_size=excluded.byte_size,sha256=excluded.sha256,width=excluded.width,height=excluded.height,local_path=excluded.local_path")
            .bind(&attachment.id).bind(thread_id).bind(&attachment.original_name).bind(&attachment.mime_type)
            .bind(&attachment.extension).bind(attachment.byte_size).bind(&attachment.sha256)
            .bind(i64::from(attachment.width)).bind(i64::from(attachment.height))
            .bind(local_path.to_string_lossy().as_ref()).bind(now()).execute(&self.pool).await?;
        Ok(AttachmentView {
            id: attachment.id.clone(),
            original_name: attachment.original_name.clone(),
            mime_type: attachment.mime_type.clone(),
            byte_size: attachment.byte_size,
            sha256: attachment.sha256.clone(),
            width: attachment.width,
            height: attachment.height,
        })
    }

    pub async fn attachment_ref(
        &self,
        attachment_id: &str,
    ) -> Result<Option<(String, AttachmentRef)>> {
        let row = sqlx::query("SELECT * FROM attachments WHERE id=?")
            .bind(attachment_id)
            .fetch_optional(&self.pool)
            .await?;
        Ok(row.map(|row| {
            let view = attachment_view_from_row(&row);
            (
                row.get("thread_id"),
                AttachmentRef {
                    id: view.id,
                    original_name: view.original_name,
                    mime_type: view.mime_type,
                    extension: row.get("extension"),
                    byte_size: view.byte_size,
                    sha256: view.sha256,
                    width: view.width,
                    height: view.height,
                },
            )
        }))
    }

    async fn item_attachments(&self, item_id: &str) -> Result<Vec<AttachmentView>> {
        let rows = sqlx::query("SELECT a.* FROM item_attachments ia JOIN attachments a ON a.id=ia.attachment_id WHERE ia.item_id=? ORDER BY ia.ordinal")
            .bind(item_id).fetch_all(&self.pool).await?;
        Ok(rows.iter().map(attachment_view_from_row).collect())
    }
    pub async fn record_agent_message(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
        app_item_id: Option<&str>,
        text: &str,
        detail: &Value,
        occurred_at: &str,
    ) -> Result<String> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let existing = if let Some(app_turn) = app_turn_id {
            sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id=?",
            )
            .bind(thread_id)
            .bind(app_turn)
            .fetch_optional(&mut *tx)
            .await?
        } else {
            None
        };
        let turn_id = if let Some(id) = existing {
            id
        } else if app_turn_id.is_none() {
            // Events without an app turn id belong to the thread's current turn;
            // only synthesize a turn when the thread has none yet.
            if let Some(id) = sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_optional(&mut *tx)
            .await?
            {
                id
            } else {
                let id = new_id("trn");
                sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,NULL,1,'active',?)").bind(&id).bind(thread_id).bind(occurred_at).execute(&mut *tx).await?;
                id
            }
        } else {
            let ordinal: i64 = sqlx::query_scalar(
                "SELECT COALESCE(MAX(ordinal),0)+1 FROM turns WHERE thread_id=?",
            )
            .bind(thread_id)
            .fetch_one(&mut *tx)
            .await?;
            let id = new_id("trn");
            sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,?,?,'active',?)").bind(&id).bind(thread_id).bind(app_turn_id).bind(ordinal).bind(occurred_at).execute(&mut *tx).await?;
            id
        };
        let encoded_detail = serde_json::to_string(detail)?;
        let existing_item = if let Some(app_item_id) = app_item_id {
            sqlx::query_scalar::<_, String>(
                "SELECT id FROM items WHERE turn_id=? AND app_server_item_id=?",
            )
            .bind(&turn_id)
            .bind(app_item_id)
            .fetch_optional(&mut *tx)
            .await?
        } else {
            None
        };
        if let Some(item_id) = existing_item {
            // Replayed item/completed notifications update the durable row in
            // place. They must never allocate a second ordinal or second id.
            sqlx::query("UPDATE items SET status='completed',content_text=?,structured_detail=?,occurred_at=CASE WHEN julianday(?)<julianday(occurred_at) THEN ? ELSE occurred_at END,completed_at=COALESCE(completed_at,?),revision=CASE WHEN content_text IS NOT ? OR structured_detail IS NOT ? THEN revision+1 ELSE revision END WHERE id=?")
                .bind(text)
                .bind(&encoded_detail)
                .bind(occurred_at)
                .bind(occurred_at)
                .bind(occurred_at)
                .bind(text)
                .bind(&encoded_detail)
                .bind(item_id)
                .execute(&mut *tx)
                .await?;
        } else {
            let ordinal: i64 =
                sqlx::query_scalar("SELECT COALESCE(MAX(ordinal),0)+1 FROM items WHERE turn_id=?")
                    .bind(&turn_id)
                    .fetch_one(&mut *tx)
                    .await?;
            let item_id = new_id("itm");
            sqlx::query("INSERT INTO items(id,turn_id,app_server_item_id,ordinal,kind,status,content_text,structured_detail,occurred_at,completed_at) VALUES(?,?,?,?,'agent_message','completed',?,?,?,?)")
                .bind(&item_id)
                .bind(&turn_id)
                .bind(app_item_id)
                .bind(ordinal)
                .bind(text)
                .bind(encoded_detail)
                .bind(occurred_at)
                .bind(occurred_at)
                .execute(&mut *tx)
                .await?;
        }
        sqlx::query(
            "UPDATE threads SET status=CASE WHEN EXISTS(SELECT 1 FROM turns WHERE thread_id=? AND status IN ('active','running','inProgress')) THEN 'active' ELSE status END,last_activity_at=CASE WHEN last_activity_at IS NULL OR julianday(?)>julianday(last_activity_at) THEN ? ELSE last_activity_at END,updated_at=CASE WHEN julianday(?)>julianday(updated_at) THEN ? ELSE updated_at END WHERE id=?",
        )
        .bind(thread_id)
        .bind(occurred_at)
        .bind(occurred_at)
        .bind(occurred_at)
        .bind(occurred_at)
        .bind(thread_id)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(turn_id)
    }
    pub async fn complete_app_turn(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
        status: &str,
    ) -> Result<()> {
        let stamp = now();
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        if let Some(app_turn_id) = app_turn_id {
            sqlx::query("UPDATE turns SET status=?,completed_at=? WHERE thread_id=? AND app_server_turn_id=?")
                .bind(status).bind(&stamp).bind(thread_id).bind(app_turn_id).execute(&mut *tx).await?;
        } else {
            sqlx::query("UPDATE turns SET status=?,completed_at=? WHERE id=(SELECT id FROM turns WHERE thread_id=? ORDER BY ordinal DESC LIMIT 1)")
                .bind(status).bind(&stamp).bind(thread_id).execute(&mut *tx).await?;
        }
        // A Codex thread has at most one executing turn. Once the authoritative
        // completion arrives, any other non-terminal row is a stale projection,
        // not evidence that work is still running.
        sqlx::query("UPDATE turns SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE thread_id=? AND status IN ('active','running','inProgress')")
            .bind(&stamp)
            .bind(thread_id)
            .execute(&mut *tx)
            .await?;
        sqlx::query("UPDATE threads SET status='idle',last_activity_at=?,updated_at=? WHERE id=?")
            .bind(&stamp)
            .bind(&stamp)
            .bind(thread_id)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(())
    }
    pub async fn import_app_thread(&self, project_id: &str, thread: &Value) -> Result<String> {
        self.import_provider_thread(AgentProvider::Codex, project_id, thread)
            .await
    }
    pub async fn import_provider_thread(
        &self,
        provider: AgentProvider,
        project_id: &str,
        thread: &Value,
    ) -> Result<String> {
        let app_id = thread
            .get("id")
            .and_then(Value::as_str)
            .ok_or_else(|| anyhow!("App Server thread has no id"))?;
        if let Some(id) = self.local_provider_thread_id(provider, app_id).await? {
            self.update_imported_thread(&id, thread).await?;
            return Ok(id);
        }
        let id = new_id("thr");
        let title = imported_thread_title(thread);
        let stamp = unix_value_to_rfc3339(thread.get("updatedAt")).unwrap_or_else(now);
        let status = value_status(thread.get("status"), "idle");
        sqlx::query("INSERT INTO threads(id,project_id,provider,app_server_thread_id,title,status,last_activity_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)")
            .bind(&id).bind(project_id).bind(provider.as_str()).bind(app_id).bind(title).bind(status).bind(&stamp).bind(&stamp).bind(&stamp)
            .execute(&self.pool).await?;
        Ok(id)
    }
    async fn update_imported_thread(&self, id: &str, thread: &Value) -> Result<()> {
        let title = imported_thread_title(thread);
        let stamp = unix_value_to_rfc3339(thread.get("updatedAt")).unwrap_or_else(now);
        let status = value_status(thread.get("status"), "idle");
        sqlx::query("UPDATE threads SET title=?,status=?,last_activity_at=CASE WHEN last_activity_at IS NULL OR julianday(?)>julianday(last_activity_at) THEN ? ELSE last_activity_at END,updated_at=CASE WHEN julianday(?)>julianday(updated_at) THEN ? ELSE updated_at END WHERE id=?")
        .bind(title)
        .bind(status)
        .bind(&stamp)
        .bind(&stamp)
        .bind(&stamp)
        .bind(&stamp)
        .bind(id)
        .execute(&self.pool)
        .await?;
        Ok(())
    }
    pub async fn import_app_history(&self, thread_id: &str, thread: &Value) -> Result<()> {
        for (turn_index, turn) in thread
            .get("turns")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .enumerate()
        {
            // Commit per turn: a whole-thread transaction can hold the WAL write lock
            // for seconds on large histories and starve interactive writes.
            let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
            let app_turn = turn
                .get("id")
                .and_then(Value::as_str)
                .ok_or_else(|| anyhow!("App Server turn has no id"))?;
            let turn_id = if let Some(id) = sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id=?",
            )
            .bind(thread_id)
            .bind(app_turn)
            .fetch_optional(&mut *tx)
            .await?
            {
                id
            } else {
                new_id("trn")
            };
            let status = value_status(turn.get("status"), "completed");
            let started = unix_value_to_rfc3339(turn.get("startedAt"));
            let completed = unix_value_to_rfc3339(turn.get("completedAt"));
            sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at,completed_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET ordinal=excluded.ordinal,status=excluded.status,started_at=COALESCE(excluded.started_at,turns.started_at),completed_at=COALESCE(excluded.completed_at,turns.completed_at)")
                .bind(&turn_id).bind(thread_id).bind(app_turn).bind(turn_index as i64+1).bind(status).bind(&started).bind(&completed).execute(&mut *tx).await?;
            let mut claimed_item_ids = HashSet::new();
            for item in turn
                .get("items")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                let app_item = item.get("id").and_then(Value::as_str).unwrap_or("");
                let raw_kind = item
                    .get("type")
                    .and_then(Value::as_str)
                    .unwrap_or("unknown");
                let kind = normalize_item_kind(raw_kind);
                let mut existing = if app_item.is_empty() {
                    None
                } else {
                    sqlx::query_scalar::<_, String>(
                        "SELECT id FROM items WHERE turn_id=? AND app_server_item_id=?",
                    )
                    .bind(&turn_id)
                    .bind(app_item)
                    .fetch_optional(&mut *tx)
                    .await?
                };
                if existing.is_none() && kind == "user_message" {
                    existing = sqlx::query_scalar::<_, String>("SELECT id FROM items WHERE turn_id=? AND kind='user_message' AND app_server_item_id IS NULL ORDER BY ordinal,id")
                        .bind(&turn_id)
                        .fetch_all(&mut *tx)
                        .await?
                        .into_iter()
                        .find(|id| !claimed_item_ids.contains(id));
                }
                let text = app_item_text(item);
                if existing.is_none()
                    && let Some(content) = text.as_deref().filter(|t| !t.is_empty())
                {
                    // The live path records the same message under the notification's item id,
                    // which does not always match the id the history endpoint returns; fall back
                    // to a content match so backfill never duplicates a recorded message.
                    existing = sqlx::query_scalar::<_, String>(
                        "SELECT id FROM items WHERE turn_id=? AND kind=? AND content_text=? ORDER BY ordinal,id",
                    )
                    .bind(&turn_id)
                    .bind(&kind)
                    .bind(content)
                    .fetch_all(&mut *tx)
                    .await?
                    .into_iter()
                    .find(|id| !claimed_item_ids.contains(id));
                }
                let item_id = existing.unwrap_or_else(|| new_id("itm"));
                claimed_item_ids.insert(item_id.clone());
                let stamp = app_item_occurred_at(item)
                    .or_else(|| started.clone())
                    .or_else(|| completed.clone())
                    .unwrap_or_else(now);
                // New rows take the next free ordinal instead of the app-side index: live-recorded
                // items (user/agent messages) already occupy ordinals, and the (turn_id, ordinal)
                // unique index must never abort the whole history import. Existing rows keep their
                // ordinal so re-imports cannot reshuffle what the live path already persisted.
                sqlx::query("INSERT INTO items(id,turn_id,app_server_item_id,ordinal,kind,status,revision,content_text,structured_detail,occurred_at,completed_at) VALUES(?,?,NULLIF(?,''),COALESCE((SELECT MAX(ordinal)+1 FROM items WHERE turn_id=?),1),?,'completed',1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET app_server_item_id=COALESCE(excluded.app_server_item_id,items.app_server_item_id),kind=excluded.kind,content_text=excluded.content_text,structured_detail=excluded.structured_detail,occurred_at=CASE WHEN julianday(excluded.occurred_at)<julianday(items.occurred_at) THEN excluded.occurred_at ELSE items.occurred_at END,completed_at=COALESCE(excluded.completed_at,items.completed_at),revision=CASE WHEN items.app_server_item_id IS NOT COALESCE(excluded.app_server_item_id,items.app_server_item_id) OR items.kind IS NOT excluded.kind OR items.content_text IS NOT excluded.content_text OR items.structured_detail IS NOT excluded.structured_detail OR (excluded.completed_at IS NOT NULL AND items.completed_at IS NOT excluded.completed_at) THEN items.revision+1 ELSE items.revision END")
                    .bind(&item_id).bind(&turn_id).bind(app_item).bind(&turn_id).bind(kind).bind(text).bind(serde_json::to_string(item)?).bind(&stamp).bind(&completed).execute(&mut *tx).await?;
                if kind == "user_message" {
                    for path in app_item_local_image_paths(item) {
                        let attachment_id: Option<String> = sqlx::query_scalar(
                            "SELECT id FROM attachments WHERE thread_id=? AND local_path=?",
                        )
                        .bind(thread_id)
                        .bind(path)
                        .fetch_optional(&mut *tx)
                        .await?;
                        if let Some(attachment_id) = attachment_id {
                            sqlx::query("INSERT OR IGNORE INTO item_attachments(item_id,attachment_id,ordinal) VALUES(?,?,COALESCE((SELECT MAX(ordinal)+1 FROM item_attachments WHERE item_id=?),1))")
                                .bind(&item_id).bind(attachment_id).bind(&item_id)
                                .execute(&mut *tx).await?;
                        }
                    }
                }
            }
            tx.commit().await?;
        }
        // `thread/read` is the upstream snapshot. Persist its thread status and
        // collapse contradictory historical turn flags before exposing the
        // snapshot to either frontend.
        let stamp = now();
        let thread_status = value_status(thread.get("status"), "idle");
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        if thread_status == "active" {
            let current: Option<String> = sqlx::query_scalar(
                "SELECT id FROM turns WHERE thread_id=? AND status IN ('active','running','inProgress') ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_optional(&mut *tx)
            .await?;
            if let Some(current) = current {
                sqlx::query("UPDATE turns SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE thread_id=? AND id<>? AND status IN ('active','running','inProgress')")
                    .bind(&stamp)
                    .bind(thread_id)
                    .bind(current)
                    .execute(&mut *tx)
                    .await?;
            }
        } else {
            sqlx::query("UPDATE turns SET status='unknown',completed_at=COALESCE(completed_at,?) WHERE thread_id=? AND status IN ('active','running','inProgress')")
                .bind(&stamp)
                .bind(thread_id)
                .execute(&mut *tx)
                .await?;
        }
        sqlx::query("UPDATE threads SET status=?,updated_at=? WHERE id=?")
            .bind(thread_status)
            .bind(&stamp)
            .bind(thread_id)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(())
    }
    pub async fn history_records(
        &self,
        thread_id: &str,
        device_id: &str,
    ) -> Result<Vec<HistoryRecord>> {
        let mut records = Vec::new();
        if let Some(thread) = self.thread(thread_id, device_id).await? {
            records.push(HistoryRecord {
                thread: Some(thread),
                turn: None,
                item: None,
            });
        }
        let turns = sqlx::query("SELECT * FROM turns WHERE thread_id=? ORDER BY COALESCE(julianday(started_at),julianday(completed_at)),ordinal,id")
            .bind(thread_id)
            .fetch_all(&self.pool)
            .await?;
        for row in turns {
            let turn = HistoryTurnView {
                id: row.get("id"),
                thread_id: row.get("thread_id"),
                ordinal: row.get("ordinal"),
                status: row.get("status"),
                started_at: row.get("started_at"),
                completed_at: row.get("completed_at"),
            };
            let turn_id = turn.id.clone();
            records.push(HistoryRecord {
                thread: None,
                turn: Some(turn),
                item: None,
            });
            let items = sqlx::query(
                "SELECT * FROM items WHERE turn_id=? ORDER BY julianday(occurred_at),ordinal,id",
            )
            .bind(&turn_id)
            .fetch_all(&self.pool)
            .await?;
            for item in items {
                let (content_text, content_truncated) = item
                    .get::<Option<String>, _>("content_text")
                    .map(|value| truncate_utf8(value, 256 * 1024))
                    .map(|(value, truncated)| (Some(value), truncated))
                    .unwrap_or((None, false));
                let mut detail = item
                    .get::<Option<String>, _>("structured_detail")
                    .and_then(|value| serde_json::from_str::<Value>(&value).ok());
                let detail_truncated = detail
                    .as_ref()
                    .and_then(|value| serde_json::to_vec(value).ok())
                    .is_some_and(|value| value.len() > 256 * 1024);
                if detail_truncated {
                    detail = Some(serde_json::json!({"truncated":true}));
                }
                records.push(HistoryRecord {
                    thread: None,
                    turn: None,
                    item: Some(HistoryItemView {
                        id: item.get("id"),
                        turn_id: item.get("turn_id"),
                        ordinal: item.get("ordinal"),
                        kind: item.get("kind"),
                        status: item.get("status"),
                        revision: item.get("revision"),
                        content_text,
                        structured_detail: detail,
                        is_truncated: content_truncated || detail_truncated,
                        occurred_at: item.get("occurred_at"),
                        completed_at: item.get("completed_at"),
                        attachments: self.item_attachments(&item.get::<String, _>("id")).await?,
                    }),
                });
            }
        }
        Ok(records)
    }

    pub async fn receive_command(
        &self,
        queue_epoch: &str,
        sequence: i64,
        target_key: &str,
        priority: i64,
        command: &DeviceCommand,
    ) -> Result<InboxRecord> {
        let json = serde_json::to_string(command)?;
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("INSERT OR IGNORE INTO command_inbox(command_id,queue_epoch,server_sequence,target_key,priority,payload,status,received_at) VALUES(?,?,?,?,?,?,'accepted',?)")
            .bind(&command.command_id).bind(queue_epoch).bind(sequence).bind(target_key).bind(priority).bind(&json).bind(now()).execute(&mut *tx).await?;
        let row = sqlx::query("SELECT * FROM command_inbox WHERE command_id=?")
            .bind(&command.command_id)
            .fetch_optional(&mut *tx)
            .await?;
        let Some(row) = row else {
            let collision: Option<String> = sqlx::query_scalar(
                "SELECT command_id FROM command_inbox WHERE queue_epoch=? AND server_sequence=?",
            )
            .bind(queue_epoch)
            .bind(sequence)
            .fetch_optional(&mut *tx)
            .await?;
            anyhow::bail!(
                "command queue identity collision: epoch={queue_epoch} sequence={sequence} existing={}",
                collision.unwrap_or_else(|| "missing".into())
            );
        };
        if row.get::<String, _>("queue_epoch") != queue_epoch
            || row.get::<i64, _>("server_sequence") != sequence
            || row.get::<String, _>("payload") != json
        {
            anyhow::bail!("command id reused with different queue identity or payload")
        }
        let record = inbox_from_row(&row)?;
        tx.commit().await?;
        Ok(record)
    }

    pub async fn enqueue_local_command(
        &self,
        target_key: &str,
        priority: i64,
        command: &DeviceCommand,
    ) -> Result<InboxRecord> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let sequence: i64 = sqlx::query_scalar("INSERT INTO runtime_state(key,value,updated_at) VALUES('next_local_command_sequence','2',?) ON CONFLICT(key) DO UPDATE SET value=CAST(runtime_state.value AS INTEGER)+1,updated_at=excluded.updated_at RETURNING CAST(value AS INTEGER)-1")
            .bind(now()).fetch_one(&mut *tx).await?;
        let json = serde_json::to_string(command)?;
        sqlx::query("INSERT INTO command_inbox(command_id,queue_epoch,server_sequence,target_key,priority,payload,status,received_at) VALUES(?,'local',?,?,?,?, 'accepted',?)")
            .bind(&command.command_id).bind(sequence).bind(target_key).bind(priority).bind(json).bind(now()).execute(&mut *tx).await?;
        let row = sqlx::query("SELECT * FROM command_inbox WHERE command_id=?")
            .bind(&command.command_id)
            .fetch_one(&mut *tx)
            .await?;
        let record = inbox_from_row(&row)?;
        tx.commit().await?;
        Ok(record)
    }

    pub async fn pending_inbox(&self, limit: i64) -> Result<Vec<InboxRecord>> {
        let rows = sqlx::query("SELECT * FROM command_inbox WHERE status='accepted' ORDER BY received_at,command_id LIMIT ?")
            .bind(limit).fetch_all(&self.pool).await?;
        rows.iter().map(inbox_from_row).collect()
    }
    pub async fn inbox(&self, id: &str) -> Result<Option<InboxRecord>> {
        let row = sqlx::query("SELECT * FROM command_inbox WHERE command_id=?")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?;
        row.as_ref().map(inbox_from_row).transpose()
    }
    pub async fn start_command(&self, id: &str) -> Result<bool> {
        Ok(sqlx::query("UPDATE command_inbox SET status='applying',started_at=? WHERE command_id=? AND status='accepted'").bind(now()).bind(id).execute(&self.pool).await?.rows_affected()==1)
    }
    pub async fn finish_command(
        &self,
        id: &str,
        queue_epoch: &str,
        sequence: i64,
        result: Option<&Value>,
        error: Option<&str>,
        error_message: Option<&str>,
    ) -> Result<()> {
        let status = if error.is_some() {
            "failed"
        } else {
            "completed"
        };
        self.finish_command_as(
            id,
            queue_epoch,
            sequence,
            status,
            result,
            error,
            error_message,
        )
        .await
    }

    pub async fn finish_command_as(
        &self,
        id: &str,
        queue_epoch: &str,
        sequence: i64,
        status: &str,
        result: Option<&Value>,
        error: Option<&str>,
        error_message: Option<&str>,
    ) -> Result<()> {
        if !matches!(status, "completed" | "failed" | "unknown" | "expired") {
            anyhow::bail!("invalid terminal command status")
        }
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("UPDATE command_inbox SET status=?,completed_at=?,result=?,error_code=?,error_message=? WHERE command_id=?").bind(status).bind(now()).bind(result.map(serde_json::to_string).transpose()?).bind(error).bind(error_message).bind(id).execute(&mut *tx).await?;
        if queue_epoch != "local" {
            let key = format!("last_server_sequence:{queue_epoch}");
            sqlx::query("INSERT INTO runtime_state(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=CASE WHEN CAST(value AS INTEGER) < ? THEN excluded.value ELSE value END,updated_at=excluded.updated_at").bind(key).bind(sequence.to_string()).bind(now()).bind(sequence).execute(&mut *tx).await?;
            sqlx::query("INSERT INTO runtime_state(key,value,updated_at) VALUES('active_command_queue_epoch',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(queue_epoch).bind(now()).execute(&mut *tx).await?;
        }
        tx.commit().await?;
        Ok(())
    }

    pub async fn enqueue_event(&self, event: &NuntiusEvent) -> Result<()> {
        sqlx::query("INSERT OR IGNORE INTO event_outbox(event_id,stream_id,sequence,payload,created_at) VALUES(?,?,?,?,?)").bind(&event.event_id).bind(&event.stream_id).bind(event.seq).bind(serde_json::to_string(event)?).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn pending_events(&self, limit: i64) -> Result<Vec<NuntiusEvent>> {
        let rows = sqlx::query("SELECT payload FROM event_outbox ORDER BY created_at LIMIT ?")
            .bind(limit)
            .fetch_all(&self.pool)
            .await?;
        rows.into_iter()
            .map(|r| Ok(serde_json::from_str(&r.get::<String, _>("payload"))?))
            .collect()
    }
    pub async fn ack_event(&self, id: &str) -> Result<()> {
        sqlx::query("DELETE FROM event_outbox WHERE event_id=?")
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn next_stream_sequence(&self, stream: &str) -> Result<i64> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("INSERT OR IGNORE INTO stream_sequences(stream_id,next_sequence) VALUES(?,1)")
            .bind(stream)
            .execute(&mut *tx)
            .await?;
        let seq: i64 =
            sqlx::query_scalar("SELECT next_sequence FROM stream_sequences WHERE stream_id=?")
                .bind(stream)
                .fetch_one(&mut *tx)
                .await?;
        sqlx::query("UPDATE stream_sequences SET next_sequence=next_sequence+1 WHERE stream_id=?")
            .bind(stream)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(seq)
    }

    pub async fn enqueue_history(&self, batch: &HistoryBatch) -> Result<()> {
        sqlx::query("INSERT OR IGNORE INTO history_outbox(batch_id,thread_id,to_cursor,payload,created_at) VALUES(?,?,?,?,?)").bind(&batch.batch_id).bind(&batch.thread_id).bind(&batch.to_cursor).bind(serde_json::to_string(batch)?).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn pending_history(&self, limit: i64) -> Result<Vec<HistoryBatch>> {
        let rows = sqlx::query("SELECT payload FROM history_outbox ORDER BY created_at LIMIT ?")
            .bind(limit)
            .fetch_all(&self.pool)
            .await?;
        rows.into_iter()
            .map(|r| Ok(serde_json::from_str(&r.get::<String, _>("payload"))?))
            .collect()
    }
    pub async fn ack_history(&self, batch_id: &str) -> Result<()> {
        sqlx::query("DELETE FROM history_outbox WHERE batch_id=?")
            .bind(batch_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    pub async fn directory_ref_create(&self, path: &Path, ttl_secs: i64) -> Result<String> {
        let id = new_id("dir");
        let expires = OffsetDateTime::now_utc().unix_timestamp() + ttl_secs;
        sqlx::query(
            "INSERT INTO directory_refs(id,canonical_path,expires_at,created_at) VALUES(?,?,?,?)",
        )
        .bind(&id)
        .bind(path.to_string_lossy().as_ref())
        .bind(expires)
        .bind(now())
        .execute(&self.pool)
        .await?;
        Ok(id)
    }
    pub async fn directory_ref_resolve(&self, id: &str) -> Result<Option<PathBuf>> {
        let now = OffsetDateTime::now_utc().unix_timestamp();
        Ok(sqlx::query_scalar::<_, String>(
            "SELECT canonical_path FROM directory_refs WHERE id=? AND expires_at>?",
        )
        .bind(id)
        .bind(now)
        .fetch_optional(&self.pool)
        .await?
        .map(PathBuf::from))
    }
    pub async fn save_app_request(
        &self,
        approval_id: &str,
        request_id: &Value,
        method: &str,
        params: &Value,
        project_id: Option<&str>,
        thread_id: Option<&str>,
    ) -> Result<()> {
        self.save_provider_request(
            AgentProvider::Codex,
            approval_id,
            request_id,
            method,
            params,
            project_id,
            thread_id,
        )
        .await
    }
    pub async fn save_provider_request(
        &self,
        provider: AgentProvider,
        approval_id: &str,
        request_id: &Value,
        method: &str,
        params: &Value,
        project_id: Option<&str>,
        thread_id: Option<&str>,
    ) -> Result<()> {
        self.save_provider_request(
            AgentProvider::Codex,
            approval_id,
            request_id,
            method,
            params,
        )
        .await
    }
    pub async fn save_provider_request(
        &self,
        provider: AgentProvider,
        approval_id: &str,
        request_id: &Value,
        method: &str,
        params: &Value,
    ) -> Result<()> {
        sqlx::query("INSERT OR IGNORE INTO pending_app_requests(approval_id,app_request_id,method,params,status,created_at,provider) VALUES(?,?,?,?,'pending',?,?)")
            .bind(approval_id)
            .bind(request_id.to_string())
            .bind(method)
            .bind(serde_json::to_string(params)?)
            .bind(now())
            .bind(provider.as_str())
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn claim_app_request(&self, approval_id: &str) -> Result<Option<(Value, String)>> {
        Ok(self
            .claim_provider_request(approval_id)
            .await?
            .map(|(_, request_id, method)| (request_id, method)))
    }
    pub async fn claim_provider_request(
        &self,
        approval_id: &str,
    ) -> Result<Option<(AgentProvider, Value, String)>> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let claimed = sqlx::query("UPDATE pending_app_requests SET status='responding' WHERE approval_id=? AND status='pending'")
            .bind(approval_id).execute(&mut *tx).await?.rows_affected();
        if claimed != 1 {
            tx.rollback().await?;
            return Ok(None);
        }
        let row = sqlx::query(
            "SELECT provider,app_request_id,method FROM pending_app_requests WHERE approval_id=?",
        )
        .bind(approval_id)
        .fetch_optional(&mut *tx)
        .await?;
        tx.commit().await?;
        row.map(|r| {
            Ok((
                provider_from_str(&r.get::<String, _>("provider")),
                serde_json::from_str(&r.get::<String, _>("app_request_id"))?,
                r.get("method"),
            ))
        })
        .transpose()
    }
    pub async fn approval_thread(&self, approval_id: &str) -> Result<Option<String>> {
        Ok(sqlx::query_scalar::<_, Option<String>>(
            "SELECT thread_id FROM pending_app_requests WHERE approval_id=?",
        )
        .bind(approval_id)
        .fetch_optional(&self.pool)
        .await?
        .flatten())
    }
    pub async fn finish_app_request(
        &self,
        approval_id: &str,
        status: &str,
        decision: Option<&str>,
        error_message: Option<&str>,
    ) -> Result<()> {
        if !matches!(status, "decided" | "unknown") {
            anyhow::bail!("invalid approval status")
        }
        sqlx::query("UPDATE pending_app_requests SET status=?,decided_at=?,decision=COALESCE(?,decision),error_message=? WHERE approval_id=? AND status='responding'")
            .bind(status)
            .bind(now())
            .bind(decision)
            .bind(error_message)
            .bind(approval_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn list_approvals(&self, device_id: &str) -> Result<Vec<ApprovalView>> {
        let rows =
            sqlx::query("SELECT * FROM pending_app_requests ORDER BY created_at DESC LIMIT 500")
                .fetch_all(&self.pool)
                .await?;
        rows.into_iter()
            .map(|row| {
                Ok(ApprovalView {
                    id: row.get("approval_id"),
                    device_id: device_id.to_owned(),
                    project_id: row.get("project_id"),
                    thread_id: row.get("thread_id"),
                    method: row.get("method"),
                    params: serde_json::from_str(&row.get::<String, _>("params"))?,
                    status: row.get("status"),
                    requested_at: row.get("created_at"),
                    decided_at: row.get("decided_at"),
                    decision: row.get("decision"),
                })
            })
            .collect()
    }
    pub async fn append_browser_event(&self, event: &NuntiusEvent) -> Result<i64> {
        let encoded = serde_json::to_string(event)?;
        let result = sqlx::query(
            "INSERT OR IGNORE INTO browser_event_journal(event_id,payload,created_at) VALUES(?,?,?)",
        )
        .bind(&event.event_id)
        .bind(&encoded)
        .bind(&event.occurred_at)
        .execute(&self.pool)
        .await?;
        if result.rows_affected() > 0 {
            return Ok(result.last_insert_rowid());
        }
        Ok(
            sqlx::query_scalar("SELECT cursor FROM browser_event_journal WHERE event_id=?")
                .bind(&event.event_id)
                .fetch_one(&self.pool)
                .await?,
        )
    }
    pub async fn browser_event_cursor(&self, event_id: &str) -> Result<Option<i64>> {
        Ok(
            sqlx::query_scalar("SELECT cursor FROM browser_event_journal WHERE event_id=?")
                .bind(event_id)
                .fetch_optional(&self.pool)
                .await?,
        )
    }
    pub async fn browser_event_bounds(&self) -> Result<(Option<i64>, Option<i64>)> {
        let row = sqlx::query(
            "SELECT MIN(cursor) minimum,MAX(cursor) maximum FROM browser_event_journal",
        )
        .fetch_one(&self.pool)
        .await?;
        Ok((row.get("minimum"), row.get("maximum")))
    }
    pub async fn replay_browser_events(
        &self,
        after: i64,
        limit: i64,
    ) -> Result<Vec<(i64, NuntiusEvent)>> {
        let rows = sqlx::query(
            "SELECT cursor,payload FROM browser_event_journal WHERE cursor>? ORDER BY cursor LIMIT ?",
        )
        .bind(after)
        .bind(limit)
        .fetch_all(&self.pool)
        .await?;
        rows.into_iter()
            .map(|row| {
                Ok((
                    row.get("cursor"),
                    serde_json::from_str(&row.get::<String, _>("payload"))?,
                ))
            })
            .collect()
    }
    pub async fn counts(&self) -> Result<(i64, i64, i64, i64)> {
        let projects = sqlx::query_scalar("SELECT COUNT(*) FROM projects WHERE status='active'")
            .fetch_one(&self.pool)
            .await?;
        let inbox = sqlx::query_scalar(
            "SELECT COUNT(*) FROM command_inbox WHERE status IN ('accepted','applying')",
        )
        .fetch_one(&self.pool)
        .await?;
        let outbox = sqlx::query_scalar(
            "SELECT (SELECT COUNT(*) FROM event_outbox)+(SELECT COUNT(*) FROM history_outbox)",
        )
        .fetch_one(&self.pool)
        .await?;
        let active = sqlx::query_scalar(
            "SELECT COUNT(*) FROM threads WHERE status IN ('active','recovering')",
        )
        .fetch_one(&self.pool)
        .await?;
        Ok((projects, inbox, outbox, active))
    }
}

fn inbox_from_row(r: &sqlx::sqlite::SqliteRow) -> Result<InboxRecord> {
    Ok(InboxRecord {
        queue_epoch: r.get("queue_epoch"),
        server_sequence: r.get("server_sequence"),
        target_key: r.get("target_key"),
        priority: r.get("priority"),
        command: serde_json::from_str(&r.get::<String, _>("payload"))?,
        status: r.get("status"),
        result: r
            .get::<Option<String>, _>("result")
            .and_then(|value| serde_json::from_str(&value).ok()),
        error_code: r.get("error_code"),
        error_message: r.get("error_message"),
    })
}

fn project_summary(r: &sqlx::sqlite::SqliteRow, device_id: &str) -> ProjectSummary {
    let path = PathBuf::from(r.get::<String, _>("canonical_path"));
    ProjectSummary {
        id: r.get("id"),
        device_id: device_id.into(),
        kind: if r.get::<String, _>("kind") == "system_unassigned" {
            ProjectKind::SystemUnassigned
        } else {
            ProjectKind::Workspace
        },
        display_name: r.get("display_name"),
        path_hint: path.file_name().map(|v| v.to_string_lossy().into_owned()),
        status: r.get("status"),
        repo_name: None,
        branch: None,
        is_dirty: None,
        thread_count: r.get("thread_count"),
        last_activity_at: Some(r.get("updated_at")),
    }
}
fn thread_summary(r: &sqlx::sqlite::SqliteRow, device_id: &str) -> ThreadSummary {
    let last_activity_at = r.get::<Option<String>, _>("last_activity_at");
    let updated_at = r.get::<String, _>("updated_at");
    let recent_activity_at = match last_activity_at {
        Some(value) if value >= updated_at => value,
        _ => updated_at,
    };
    ThreadSummary {
        id: r.get("id"),
        device_id: device_id.into(),
        project_id: r.get("project_id"),
        provider: provider_from_str(&r.get::<String, _>("provider")),
        app_server_thread_id: r.get("app_server_thread_id"),
        title: r.get("title"),
        status: r.get("status"),
        archived: r.get("archived"),
        history_completeness: HistoryCompleteness::Complete,
        last_synced_at: None,
        last_activity_at: Some(recent_activity_at),
    }
}

fn provider_from_str(value: &str) -> AgentProvider {
    if value == "kimi" {
        AgentProvider::Kimi
    } else {
        AgentProvider::Codex
    }
}

fn provider_from_str(value: &str) -> AgentProvider {
    if value == "kimi" {
        AgentProvider::Kimi
    } else {
        AgentProvider::Codex
    }
}

fn attachment_view_from_row(r: &sqlx::sqlite::SqliteRow) -> AttachmentView {
    AttachmentView {
        id: r.get("id"),
        original_name: r.get("original_name"),
        mime_type: r.get("mime_type"),
        byte_size: r.get("byte_size"),
        sha256: r.get("sha256"),
        width: r.get::<i64, _>("width") as u32,
        height: r.get::<i64, _>("height") as u32,
    }
}

fn imported_thread_title(thread: &Value) -> &str {
    thread
        .get("name")
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .or_else(|| {
            thread
                .get("preview")
                .and_then(Value::as_str)
                .filter(|value| !value.is_empty())
        })
        .unwrap_or("历史对话")
}

fn value_status(value: Option<&Value>, fallback: &str) -> String {
    value
        .and_then(|value| {
            value
                .as_str()
                .or_else(|| value.get("type").and_then(Value::as_str))
        })
        .unwrap_or(fallback)
        .to_string()
}

fn unix_value_to_rfc3339(value: Option<&Value>) -> Option<String> {
    let value = value?;
    if let Some(text) = value.as_str() {
        return OffsetDateTime::parse(text, &time::format_description::well_known::Rfc3339)
            .ok()?
            .format(&time::format_description::well_known::Rfc3339)
            .ok();
    }
    let raw = value.as_i64()?;
    // App Server versions have used seconds and milliseconds in different
    // payloads. Normalize both before persisting so every consumer parses the
    // same instant rather than comparing untyped integers.
    let (seconds, nanos) = if raw.abs() >= 10_000_000_000 {
        (
            raw.div_euclid(1_000),
            raw.rem_euclid(1_000) as i128 * 1_000_000,
        )
    } else {
        (raw, 0)
    };
    OffsetDateTime::from_unix_timestamp(seconds)
        .ok()?
        .replace_nanosecond(nanos as u32)
        .ok()?
        .format(&time::format_description::well_known::Rfc3339)
        .ok()
}

fn app_item_occurred_at(item: &Value) -> Option<String> {
    ["occurredAt", "createdAt", "startedAt", "timestamp"]
        .into_iter()
        .find_map(|field| unix_value_to_rfc3339(item.get(field)))
}

fn app_item_text(item: &Value) -> Option<String> {
    if let Some(text) = item.get("text").and_then(Value::as_str) {
        return Some(text.into());
    }
    let content = item.get("content")?.as_array()?;
    let parts = content
        .iter()
        .filter_map(|part| part.get("text").and_then(Value::as_str))
        .collect::<Vec<_>>();
    (!parts.is_empty()).then(|| parts.join("\n"))
}

fn app_item_local_image_paths(item: &Value) -> Vec<&str> {
    item.get("content")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter(|part| part.get("type").and_then(Value::as_str) == Some("localImage"))
        .filter_map(|part| part.get("path").and_then(Value::as_str))
        .collect()
}

fn normalize_item_kind(kind: &str) -> &str {
    match kind {
        "userMessage" => "user_message",
        "agentMessage" => "agent_message",
        "commandExecution" => "command_execution",
        "fileChange" => "file_change",
        other => other,
    }
}

fn truncate_utf8(value: String, max_bytes: usize) -> (String, bool) {
    if value.len() <= max_bytes {
        return (value, false);
    }
    let mut boundary = max_bytes;
    while !value.is_char_boundary(boundary) {
        boundary -= 1;
    }
    (value[..boundary].to_string(), true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[tokio::test]
    async fn threads_are_sorted_by_the_newest_update_or_conversation() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_recent", "Recent", &workspace, &json!({}))
            .await
            .unwrap();

        for (id, app_id) in [
            ("thr_created", "app_created"),
            ("thr_updated", "app_updated"),
            ("thr_conversation", "app_conversation"),
        ] {
            store
                .create_thread(id, "prj_recent", app_id, id, &json!({}))
                .await
                .unwrap();
        }

        sqlx::query(
            "UPDATE threads SET last_activity_at='2026-07-19T08:00:00Z',updated_at='2026-07-19T08:00:00Z' WHERE id='thr_created'",
        )
        .execute(&store.pool)
        .await
        .unwrap();
        sqlx::query(
            "UPDATE threads SET last_activity_at='2026-07-19T08:00:00Z',updated_at='2026-07-19T10:00:00Z' WHERE id='thr_updated'",
        )
        .execute(&store.pool)
        .await
        .unwrap();
        sqlx::query(
            "UPDATE threads SET last_activity_at='2026-07-19T11:00:00Z',updated_at='2026-07-19T09:00:00Z' WHERE id='thr_conversation'",
        )
        .execute(&store.pool)
        .await
        .unwrap();

        let threads = store.list_threads("dev_test", None).await.unwrap();
        assert_eq!(
            threads
                .iter()
                .map(|thread| thread.id.as_str())
                .collect::<Vec<_>>(),
            vec!["thr_conversation", "thr_updated", "thr_created"]
        );
        assert_eq!(
            threads[0].last_activity_at.as_deref(),
            Some("2026-07-19T11:00:00Z")
        );
        assert_eq!(
            threads[1].last_activity_at.as_deref(),
            Some("2026-07-19T10:00:00Z")
        );
    }

    #[tokio::test]
    async fn archived_threads_remain_stored_but_leave_active_lists() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_archive", "Archive", &workspace, &json!({}))
            .await
            .unwrap();
        store
            .create_thread(
                "thr_archive",
                "prj_archive",
                "app_archive",
                "Keep me",
                &json!({}),
            )
            .await
            .unwrap();

        store
            .set_thread_archived("thr_archive", true)
            .await
            .unwrap();

        assert!(
            store
                .list_threads("dev_test", None)
                .await
                .unwrap()
                .is_empty()
        );
        assert!(
            store
                .controllable_thread("thr_archive", "dev_test")
                .await
                .unwrap()
                .is_none()
        );
        assert!(
            store
                .thread("thr_archive", "dev_test")
                .await
                .unwrap()
                .unwrap()
                .archived
        );
        assert_eq!(
            store.list_projects("dev_test").await.unwrap()[0].thread_count,
            0
        );
    }

    #[tokio::test]
    async fn project_removal_cleans_records_and_blocks_automatic_reimport() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_remove", "Remove me", &workspace, &json!({}))
            .await
            .unwrap();
        store
            .create_thread(
                "thr_remove",
                "prj_remove",
                "app_remove",
                "Old thread",
                &json!({}),
            )
            .await
            .unwrap();
        store
            .enqueue_event(&NuntiusEvent {
                event_id: "evt_old_summary".into(),
                user_id: None,
                device_id: "dev_test".into(),
                project_id: Some("prj_remove".into()),
                thread_id: None,
                turn_id: None,
                stream_id: "device:dev_test".into(),
                seq: 1,
                event_type: "project.summary".into(),
                durability: "durable".into(),
                occurred_at: now(),
                payload: json!({"id":"prj_remove"}),
            })
            .await
            .unwrap();

        let removed = store.remove_project("prj_remove").await.unwrap().unwrap();
        assert_eq!(removed.thread_count, 1);
        assert!(!removed.already_removed);
        assert!(
            store
                .project("prj_remove", "dev_test")
                .await
                .unwrap()
                .is_none()
        );
        assert!(
            store
                .list_threads("dev_test", None)
                .await
                .unwrap()
                .is_empty()
        );
        assert!(store.project_path_removed(&workspace).await.unwrap());
        assert!(store.app_thread_removed("app_remove").await.unwrap());
        assert!(store.pending_events(10).await.unwrap().is_empty());

        let replay = store.remove_project("prj_remove").await.unwrap().unwrap();
        assert!(replay.already_removed);

        store
            .create_project("prj_readded", "Re-added", &workspace, &json!({}))
            .await
            .unwrap();
        assert!(!store.project_path_removed(&workspace).await.unwrap());
        assert!(!store.app_thread_removed("app_remove").await.unwrap());

        let unassigned = store.ensure_unassigned_project("dev_test").await.unwrap();
        assert!(store.remove_project(&unassigned).await.is_err());
    }

    #[tokio::test]
    async fn process_recovery_preserves_running_thread_candidates() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_recovery", "Recovery", &workspace, &json!({}))
            .await
            .unwrap();
        for (local_id, app_id, turn_id) in [
            ("thr_active", "app_active", "turn_active"),
            ("thr_legacy", "app_legacy", "turn_legacy"),
        ] {
            store
                .create_thread(local_id, "prj_recovery", app_id, "Recover me", &json!({}))
                .await
                .unwrap();
            store
                .mark_app_turn_started(local_id, Some(turn_id))
                .await
                .unwrap();
        }
        // Previous releases changed only the thread to `unknown`, leaving the
        // active turn behind. Upgrades must recover that legacy state too.
        store
            .set_thread_status("thr_legacy", "unknown")
            .await
            .unwrap();

        let candidates = store.recover_process_state().await.unwrap();
        assert_eq!(candidates, vec!["thr_active", "thr_legacy"]);
        for thread_id in candidates {
            assert_eq!(
                store
                    .thread(thread_id, "dev_test")
                    .await
                    .unwrap()
                    .unwrap()
                    .status,
                "recovering"
            );
            let completed_at: Option<String> = sqlx::query_scalar(
                "SELECT completed_at FROM turns WHERE thread_id=? ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_one(&store.pool)
            .await
            .unwrap();
            assert!(completed_at.is_none());
        }
    }

    #[tokio::test]
    async fn authoritative_runtime_state_keeps_only_one_active_turn() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_runtime", "Runtime", &workspace, &json!({}))
            .await
            .unwrap();
        store
            .create_thread(
                "thr_runtime",
                "prj_runtime",
                "app_runtime",
                "Runtime",
                &json!({}),
            )
            .await
            .unwrap();

        store
            .mark_app_turn_started("thr_runtime", Some("app_turn_one"))
            .await
            .unwrap();
        store
            .mark_app_turn_started("thr_runtime", Some("app_turn_two"))
            .await
            .unwrap();
        let active: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM turns WHERE thread_id='thr_runtime' AND status IN ('active','running','inProgress')",
        )
        .fetch_one(&store.pool)
        .await
        .unwrap();
        assert_eq!(active, 1);
        assert_eq!(
            store
                .thread("thr_runtime", "dev_test")
                .await
                .unwrap()
                .unwrap()
                .status,
            "active"
        );

        store
            .complete_app_turn("thr_runtime", Some("app_turn_two"), "completed")
            .await
            .unwrap();
        let active: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM turns WHERE thread_id='thr_runtime' AND status IN ('active','running','inProgress')",
        )
        .fetch_one(&store.pool)
        .await
        .unwrap();
        assert_eq!(active, 0);
        assert_eq!(
            store
                .thread("thr_runtime", "dev_test")
                .await
                .unwrap()
                .unwrap()
                .status,
            "idle"
        );

        store
            .import_app_history(
                "thr_runtime",
                &json!({
                    "status":"active",
                    "turns":[
                        {"id":"app_turn_one","status":"inProgress","items":[]},
                        {"id":"app_turn_two","status":"inProgress","items":[]}
                    ]
                }),
            )
            .await
            .unwrap();
        let active: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM turns WHERE thread_id='thr_runtime' AND status IN ('active','running','inProgress')",
        )
        .fetch_one(&store.pool)
        .await
        .unwrap();
        assert_eq!(active, 1);
    }

    #[tokio::test]
    async fn durable_inbox_outbox_and_history_round_trip() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_test", "Test", &workspace, &json!({}))
            .await
            .unwrap();
        store
            .create_thread(
                "thr_test",
                "prj_test",
                "app_thread",
                "Thread",
                &json!({"sandbox":"danger-full-access"}),
            )
            .await
            .unwrap();
        assert!(!store.thread_has_turns("thr_test").await.unwrap());
        assert_eq!(
            store.app_server_options("thr_test").await.unwrap(),
            json!({"sandbox":"danger-full-access"})
        );
        store
            .rebind_app_server_thread("thr_test", "app_thread_rebound")
            .await
            .unwrap();
        assert_eq!(
            store
                .thread("thr_test", "dev_test")
                .await
                .unwrap()
                .unwrap()
                .app_server_thread_id
                .as_deref(),
            Some("app_thread_rebound")
        );
        store
            .record_user_turn("thr_test", Some("app_turn"), "hello", &[])
            .await
            .unwrap();
        store
            .record_agent_message(
                "thr_test",
                Some("app_turn"),
                Some("app_item"),
                "world",
                &json!({"type":"agentMessage"}),
                &now(),
            )
            .await
            .unwrap();
        store
            .record_agent_message(
                "thr_test",
                Some("app_turn"),
                Some("app_item"),
                "world",
                &json!({"type":"agentMessage"}),
                &now(),
            )
            .await
            .unwrap();
        store
            .import_app_history(
                "thr_test",
                &json!({"turns":[{"id":"app_turn","status":"completed","items":[
                    {"id":"app_user","type":"userMessage","content":[{"type":"text","text":"hello"}]},
                    {"id":"app_item","type":"agentMessage","text":"world"},
                    {"id":"app_item_repeat","type":"agentMessage","text":"world"}
                ]}]}),
            )
            .await
            .unwrap();
        let history = store.history_records("thr_test", "dev_test").await.unwrap();
        assert!(history.iter().any(|record| record.thread.is_some()));
        assert_eq!(
            history
                .iter()
                .filter(|record| record.item.is_some())
                .count(),
            3
        );
        let revisions_before = history
            .iter()
            .filter_map(|record| record.item.as_ref().map(|item| item.revision))
            .collect::<Vec<_>>();
        store
            .import_app_history(
                "thr_test",
                &json!({"turns":[{"id":"app_turn","status":"completed","items":[
                    {"id":"app_user","type":"userMessage","content":[{"type":"text","text":"hello"}]},
                    {"id":"app_item","type":"agentMessage","text":"world"},
                    {"id":"app_item_repeat","type":"agentMessage","text":"world"}
                ]}]}),
            )
            .await
            .unwrap();
        let revisions_after = store
            .history_records("thr_test", "dev_test")
            .await
            .unwrap()
            .into_iter()
            .filter_map(|record| record.item.map(|item| item.revision))
            .collect::<Vec<_>>();
        assert_eq!(revisions_after, revisions_before);

        let command = DeviceCommand {
            command_id: "cmd_test".into(),
            device_id: "dev_test".into(),
            project_id: None,
            thread_id: None,
            issued_at: now(),
            expires_at: now(),
            command: DeviceCommandKind::Refresh,
        };
        assert_eq!(
            store
                .receive_command("epoch_test", 1, "device:dev_test", 2, &command)
                .await
                .unwrap()
                .status,
            "accepted"
        );
        assert!(store.start_command("cmd_test").await.unwrap());
        store
            .finish_command(
                "cmd_test",
                "epoch_test",
                1,
                Some(&json!({"ok":true})),
                None,
                None,
            )
            .await
            .unwrap();
        assert_eq!(
            store
                .receive_command("epoch_test", 1, "device:dev_test", 2, &command)
                .await
                .unwrap()
                .status,
            "completed"
        );
        assert_eq!(
            store
                .last_server_sequence(Some("epoch_test"))
                .await
                .unwrap(),
            1
        );

        let next_epoch = DeviceCommand {
            command_id: "cmd_next_epoch".into(),
            ..command.clone()
        };
        assert_eq!(
            store
                .receive_command("epoch_next", 1, "device:dev_test", 2, &next_epoch)
                .await
                .unwrap()
                .status,
            "accepted"
        );
        let collision = DeviceCommand {
            command_id: "cmd_collision".into(),
            ..command.clone()
        };
        assert!(
            store
                .receive_command("epoch_test", 1, "device:dev_test", 2, &collision)
                .await
                .is_err()
        );
        let local = DeviceCommand {
            command_id: "cmd_local".into(),
            ..command.clone()
        };
        let local_record = store
            .enqueue_local_command("device:dev_test", 2, &local)
            .await
            .unwrap();
        assert_eq!(local_record.queue_epoch, "local");

        let unassigned = store.ensure_unassigned_project("dev_test").await.unwrap();
        assert_eq!(
            store.ensure_unassigned_project("dev_test").await.unwrap(),
            unassigned
        );
        let uncertain = DeviceCommand {
            command_id: "cmd_uncertain".into(),
            device_id: "dev_test".into(),
            project_id: None,
            thread_id: None,
            issued_at: now(),
            expires_at: now(),
            command: DeviceCommandKind::Refresh,
        };
        store
            .receive_command("epoch_test", 2, "device:dev_test", 2, &uncertain)
            .await
            .unwrap();
        assert!(store.start_command("cmd_uncertain").await.unwrap());
        store.recover_process_state().await.unwrap();
        assert_eq!(
            store.inbox("cmd_uncertain").await.unwrap().unwrap().status,
            "unknown"
        );

        let retryable_archive = DeviceCommand {
            command_id: "cmd_retryable_archive".into(),
            thread_id: Some("thr_test".into()),
            command: DeviceCommandKind::ThreadArchive {
                thread_id: "thr_test".into(),
                archived: true,
            },
            ..command.clone()
        };
        store
            .receive_command("epoch_test", 3, "thread:thr_test", 2, &retryable_archive)
            .await
            .unwrap();
        assert!(store.start_command("cmd_retryable_archive").await.unwrap());
        store.recover_process_state().await.unwrap();
        assert_eq!(
            store
                .inbox("cmd_retryable_archive")
                .await
                .unwrap()
                .unwrap()
                .status,
            "accepted"
        );

        store
            .save_app_request(
                "apr_test",
                &json!(42),
                "item/commandExecution/requestApproval",
                &json!({}),
                None,
                None,
            )
            .await
            .unwrap();
        assert!(store.claim_app_request("apr_test").await.unwrap().is_some());
        assert!(store.claim_app_request("apr_test").await.unwrap().is_none());
        store
            .finish_app_request("apr_test", "decided", Some("accept"), None)
            .await
            .unwrap();

        let event = NuntiusEvent {
            event_id: "evt_test".into(),
            user_id: None,
            device_id: "dev_test".into(),
            project_id: None,
            thread_id: None,
            turn_id: None,
            stream_id: "device:dev_test".into(),
            seq: 1,
            event_type: "test".into(),
            durability: "durable".into(),
            occurred_at: now(),
            payload: json!({}),
        };
        store.enqueue_event(&event).await.unwrap();
        assert_eq!(store.pending_events(10).await.unwrap().len(), 1);
        store.ack_event("evt_test").await.unwrap();
        assert!(store.pending_events(10).await.unwrap().is_empty());
        let backup = temp.path().join("backup.db");
        store.backup(&backup).await.unwrap();
        assert!(backup.is_file());
    }
}
