use crate::{config::DATABASE_FILE, protocol::*};
use anyhow::{Result, anyhow};
use serde_json::Value;
use sqlx::{
    ConnectOptions, Row, SqlitePool,
    sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous},
};
use std::{
    path::{Path, PathBuf},
    str::FromStr,
};
use time::OffsetDateTime;

#[derive(Clone)]
pub struct ClientStore {
    pool: SqlitePool,
}
#[derive(Debug, Clone)]
pub struct ProjectRecord {
    pub summary: ProjectSummary,
    pub canonical_path: PathBuf,
    pub defaults: Value,
}
#[derive(Debug, Clone)]
pub struct InboxRecord {
    pub queue_epoch: String,
    pub server_sequence: i64,
    pub target_key: String,
    pub priority: i64,
    pub command: DeviceCommand,
    pub status: String,
    pub result: Option<Value>,
    pub error_code: Option<String>,
    pub error_message: Option<String>,
}

impl ClientStore {
    pub async fn open(root: &Path) -> Result<Self> {
        let path = root.join(DATABASE_FILE);
        let url = format!("sqlite://{}", path.to_string_lossy());
        let options = SqliteConnectOptions::from_str(&url)?
            .create_if_missing(true)
            .journal_mode(SqliteJournalMode::Wal)
            .synchronous(SqliteSynchronous::Full)
            .foreign_keys(true)
            .busy_timeout(std::time::Duration::from_secs(15))
            .disable_statement_logging();
        let pool = SqlitePoolOptions::new()
            .max_connections(4)
            .connect_with(options)
            .await?;
        sqlx::migrate!("./migrations").run(&pool).await?;
        crate::config::private_file(&path)?;
        for suffix in ["-wal", "-shm"] {
            let sidecar = PathBuf::from(format!("{}{suffix}", path.display()));
            if sidecar.exists() {
                crate::config::private_file(&sidecar)?;
            }
        }
        Ok(Self { pool })
    }
    pub async fn ready(&self) -> Result<()> {
        sqlx::query("SELECT 1").execute(&self.pool).await?;
        Ok(())
    }
    pub async fn maintenance(&self) -> Result<()> {
        sqlx::query("DELETE FROM directory_refs WHERE expires_at<=?")
            .bind(OffsetDateTime::now_utc().unix_timestamp())
            .execute(&self.pool)
            .await?;
        sqlx::query("PRAGMA wal_checkpoint(PASSIVE)")
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn backup(&self, destination: &Path) -> Result<()> {
        if destination.exists() {
            anyhow::bail!(
                "backup destination already exists: {}",
                destination.display()
            );
        }
        let escaped = destination.to_string_lossy().replace('\'', "''");
        // `destination` is generated by the CLI inside the private data directory;
        // single quotes are escaped above before opting this dynamic SQLite
        // statement out of SQLx's static SQL check.
        sqlx::query(sqlx::AssertSqlSafe(format!("VACUUM INTO '{escaped}'")))
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn recover_process_state(&self) -> Result<()> {
        let stamp = now();
        sqlx::query(
            "UPDATE pending_app_requests SET status='unknown',decided_at=? WHERE status IN ('pending','responding')",
        )
        .bind(&stamp)
        .execute(&self.pool)
        .await?;
        sqlx::query("UPDATE threads SET status='unknown',updated_at=? WHERE status='active'")
            .bind(&stamp)
            .execute(&self.pool)
            .await?;
        sqlx::query("UPDATE command_inbox SET status='unknown',completed_at=?,error_code='execution_state_unknown_after_restart',error_message='客户端重启，无法确认命令是否已经执行' WHERE status='applying'")
            .bind(&stamp)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn pending_approval_count(&self) -> Result<i64> {
        Ok(
            sqlx::query_scalar("SELECT COUNT(*) FROM pending_app_requests WHERE status='pending'")
                .fetch_one(&self.pool)
                .await?,
        )
    }
    pub async fn state_get(&self, key: &str) -> Result<Option<String>> {
        Ok(
            sqlx::query_scalar("SELECT value FROM runtime_state WHERE key=?")
                .bind(key)
                .fetch_optional(&self.pool)
                .await?,
        )
    }
    pub async fn state_set(&self, key: &str, value: &str) -> Result<()> {
        sqlx::query("INSERT INTO runtime_state(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(key).bind(value).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn next_history_revision(&self, thread_id: &str) -> Result<i64> {
        let key = format!("history_revision:{thread_id}");
        let revision: String = sqlx::query_scalar("INSERT INTO runtime_state(key,value,updated_at) VALUES(?,'1',?) ON CONFLICT(key) DO UPDATE SET value=CAST(runtime_state.value AS INTEGER)+1,updated_at=excluded.updated_at RETURNING value")
            .bind(key).bind(now()).fetch_one(&self.pool).await?;
        Ok(revision.parse()?)
    }
    pub async fn active_command_queue_epoch(&self) -> Result<Option<String>> {
        self.state_get("active_command_queue_epoch").await
    }
    pub async fn last_server_sequence(&self, queue_epoch: Option<&str>) -> Result<i64> {
        let key = queue_epoch
            .map(|epoch| format!("last_server_sequence:{epoch}"))
            .unwrap_or_else(|| "last_server_sequence".into());
        Ok(self
            .state_get(&key)
            .await?
            .and_then(|v| v.parse().ok())
            .unwrap_or(0))
    }

    pub async fn list_projects(&self, device_id: &str) -> Result<Vec<ProjectSummary>> {
        let rows=sqlx::query("SELECT p.*,(SELECT COUNT(*) FROM threads t WHERE t.project_id=p.id) thread_count FROM projects p WHERE status='active' ORDER BY updated_at DESC").fetch_all(&self.pool).await?;
        Ok(rows
            .into_iter()
            .map(|r| project_summary(&r, device_id))
            .collect())
    }
    pub async fn project(&self, id: &str, device_id: &str) -> Result<Option<ProjectRecord>> {
        let row=sqlx::query("SELECT p.*,(SELECT COUNT(*) FROM threads t WHERE t.project_id=p.id) thread_count FROM projects p WHERE id=? AND status='active'").bind(id).fetch_optional(&self.pool).await?;
        Ok(row.map(|r| ProjectRecord {
            canonical_path: PathBuf::from(r.get::<String, _>("canonical_path")),
            defaults: serde_json::from_str(&r.get::<String, _>("defaults_json"))
                .unwrap_or(Value::Object(Default::default())),
            summary: project_summary(&r, device_id),
        }))
    }
    pub async fn project_by_path(&self, path: &Path) -> Result<Option<String>> {
        Ok(
            sqlx::query_scalar(
                "SELECT id FROM projects WHERE canonical_path=? AND status='active'",
            )
            .bind(path.to_string_lossy().as_ref())
            .fetch_optional(&self.pool)
            .await?,
        )
    }
    pub async fn ensure_unassigned_project(&self, device_id: &str) -> Result<String> {
        if let Some(id) =
            sqlx::query_scalar("SELECT id FROM projects WHERE kind='system_unassigned' LIMIT 1")
                .fetch_optional(&self.pool)
                .await?
        {
            return Ok(id);
        }
        let id = new_id("prj_unassigned");
        let stamp = now();
        let path = format!("nuntius://system-unassigned/{device_id}");
        sqlx::query("INSERT INTO projects(id,kind,display_name,canonical_path,status,defaults_json,created_at,updated_at) VALUES(?,'system_unassigned','未归类',?,'system_unassigned','{}',?,?)")
            .bind(&id).bind(path).bind(&stamp).bind(&stamp).execute(&self.pool).await?;
        Ok(id)
    }
    pub async fn create_project(
        &self,
        id: &str,
        name: &str,
        path: &Path,
        defaults: &Value,
    ) -> Result<()> {
        let stamp = now();
        sqlx::query("INSERT INTO projects(id,display_name,canonical_path,defaults_json,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(id).bind(name).bind(path.to_string_lossy().as_ref()).bind(serde_json::to_string(defaults)?).bind(&stamp).bind(&stamp).execute(&self.pool).await?;
        Ok(())
    }

    pub async fn list_threads(
        &self,
        device_id: &str,
        project_id: Option<&str>,
    ) -> Result<Vec<ThreadSummary>> {
        self.list_threads_page(device_id, project_id, -1, 0).await
    }
    pub async fn list_threads_page(
        &self,
        device_id: &str,
        project_id: Option<&str>,
        limit: i64,
        offset: i64,
    ) -> Result<Vec<ThreadSummary>> {
        let rows = if let Some(project) = project_id {
            sqlx::query("SELECT * FROM threads WHERE project_id=? ORDER BY COALESCE(last_activity_at,created_at) DESC,id DESC LIMIT ? OFFSET ?").bind(project).bind(limit).bind(offset).fetch_all(&self.pool).await?
        } else {
            sqlx::query("SELECT * FROM threads ORDER BY COALESCE(last_activity_at,created_at) DESC,id DESC LIMIT ? OFFSET ?").bind(limit).bind(offset).fetch_all(&self.pool).await?
        };
        Ok(rows
            .into_iter()
            .map(|r| thread_summary(&r, device_id))
            .collect())
    }
    pub async fn thread(&self, id: &str, device_id: &str) -> Result<Option<ThreadSummary>> {
        Ok(sqlx::query("SELECT * FROM threads WHERE id=?")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?
            .map(|r| thread_summary(&r, device_id)))
    }
    pub async fn controllable_thread(
        &self,
        id: &str,
        device_id: &str,
    ) -> Result<Option<ThreadSummary>> {
        Ok(sqlx::query("SELECT t.* FROM threads t JOIN projects p ON p.id=t.project_id WHERE t.id=? AND p.kind='workspace' AND p.status='active'")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?
            .map(|row| thread_summary(&row, device_id)))
    }
    pub async fn create_thread(
        &self,
        id: &str,
        project_id: &str,
        app_id: &str,
        title: &str,
        app_server_options: &Value,
    ) -> Result<()> {
        let stamp = now();
        sqlx::query("INSERT INTO threads(id,project_id,app_server_thread_id,title,app_server_options,last_activity_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(id).bind(project_id).bind(app_id).bind(title).bind(serde_json::to_string(app_server_options)?).bind(&stamp).bind(&stamp).bind(&stamp).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn thread_has_turns(&self, id: &str) -> Result<bool> {
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM turns WHERE thread_id=?")
            .bind(id)
            .fetch_one(&self.pool)
            .await?;
        Ok(count > 0)
    }
    pub async fn app_server_options(&self, id: &str) -> Result<Value> {
        let encoded: String =
            sqlx::query_scalar("SELECT app_server_options FROM threads WHERE id=?")
                .bind(id)
                .fetch_one(&self.pool)
                .await?;
        Ok(serde_json::from_str(&encoded).unwrap_or_else(|_| Value::Object(Default::default())))
    }
    pub async fn rebind_app_server_thread(&self, id: &str, app_id: &str) -> Result<()> {
        sqlx::query(
            "UPDATE threads SET app_server_thread_id=?,status='idle',updated_at=? WHERE id=?",
        )
        .bind(app_id)
        .bind(now())
        .bind(id)
        .execute(&self.pool)
        .await?;
        Ok(())
    }
    pub async fn set_thread_archived(&self, id: &str, archived: bool) -> Result<()> {
        sqlx::query("UPDATE threads SET archived=?,updated_at=? WHERE id=?")
            .bind(archived)
            .bind(now())
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    /// App-server turn id of the thread's currently active turn, if any.
    pub async fn active_app_turn_id(&self, thread_id: &str) -> Result<Option<String>> {
        Ok(sqlx::query_scalar(
            "SELECT app_server_turn_id FROM turns WHERE thread_id=? AND status='active' AND app_server_turn_id IS NOT NULL ORDER BY ordinal DESC LIMIT 1",
        )
        .bind(thread_id)
        .fetch_optional(&self.pool)
        .await?)
    }
    pub async fn touch_thread(&self, id: &str, status: &str) -> Result<()> {
        sqlx::query("UPDATE threads SET status=?,last_activity_at=?,updated_at=? WHERE id=?")
            .bind(status)
            .bind(now())
            .bind(now())
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn local_thread_id(&self, app_thread_id: &str) -> Result<Option<String>> {
        Ok(
            sqlx::query_scalar("SELECT id FROM threads WHERE app_server_thread_id=?")
                .bind(app_thread_id)
                .fetch_optional(&self.pool)
                .await?,
        )
    }
    pub async fn record_user_turn(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
        text: &str,
    ) -> Result<String> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let ordinal: i64 =
            sqlx::query_scalar("SELECT COALESCE(MAX(ordinal),0)+1 FROM turns WHERE thread_id=?")
                .bind(thread_id)
                .fetch_one(&mut *tx)
                .await?;
        let turn_id = new_id("trn");
        let item_id = new_id("itm");
        let stamp = now();
        sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,?,?,'active',?)").bind(&turn_id).bind(thread_id).bind(app_turn_id).bind(ordinal).bind(&stamp).execute(&mut *tx).await?;
        sqlx::query("INSERT INTO items(id,turn_id,ordinal,kind,status,content_text,occurred_at,completed_at) VALUES(?, ?, 1, 'user_message', 'completed', ?, ?, ?)").bind(item_id).bind(&turn_id).bind(text).bind(&stamp).bind(&stamp).execute(&mut *tx).await?;
        sqlx::query(
            "UPDATE threads SET status='active',last_activity_at=?,updated_at=? WHERE id=?",
        )
        .bind(&stamp)
        .bind(&stamp)
        .bind(thread_id)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(turn_id)
    }
    pub async fn record_agent_message(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
        app_item_id: Option<&str>,
        text: &str,
        detail: &Value,
    ) -> Result<String> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let existing = if let Some(app_turn) = app_turn_id {
            sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id=?",
            )
            .bind(thread_id)
            .bind(app_turn)
            .fetch_optional(&mut *tx)
            .await?
        } else {
            None
        };
        let turn_id = if let Some(id) = existing {
            id
        } else if app_turn_id.is_none() {
            // Events without an app turn id belong to the thread's current turn;
            // only synthesize a turn when the thread has none yet.
            if let Some(id) = sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? ORDER BY ordinal DESC LIMIT 1",
            )
            .bind(thread_id)
            .fetch_optional(&mut *tx)
            .await?
            {
                id
            } else {
                let id = new_id("trn");
                sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,NULL,1,'active',?)").bind(&id).bind(thread_id).bind(now()).execute(&mut *tx).await?;
                id
            }
        } else {
            let ordinal: i64 = sqlx::query_scalar(
                "SELECT COALESCE(MAX(ordinal),0)+1 FROM turns WHERE thread_id=?",
            )
            .bind(thread_id)
            .fetch_one(&mut *tx)
            .await?;
            let id = new_id("trn");
            sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at) VALUES(?,?,?,?,'active',?)").bind(&id).bind(thread_id).bind(app_turn_id).bind(ordinal).bind(now()).execute(&mut *tx).await?;
            id
        };
        let ordinal: i64 =
            sqlx::query_scalar("SELECT COALESCE(MAX(ordinal),0)+1 FROM items WHERE turn_id=?")
                .bind(&turn_id)
                .fetch_one(&mut *tx)
                .await?;
        let item_id = new_id("itm");
        let stamp = now();
        sqlx::query("INSERT OR IGNORE INTO items(id,turn_id,app_server_item_id,ordinal,kind,status,content_text,structured_detail,occurred_at,completed_at) VALUES(?,?,?,?,'agent_message','completed',?,?,?,?)").bind(&item_id).bind(&turn_id).bind(app_item_id).bind(ordinal).bind(text).bind(serde_json::to_string(detail)?).bind(&stamp).bind(&stamp).execute(&mut *tx).await?;
        sqlx::query(
            "UPDATE threads SET status='active',last_activity_at=?,updated_at=? WHERE id=?",
        )
        .bind(&stamp)
        .bind(&stamp)
        .bind(thread_id)
        .execute(&mut *tx)
        .await?;
        tx.commit().await?;
        Ok(turn_id)
    }
    pub async fn complete_app_turn(
        &self,
        thread_id: &str,
        app_turn_id: Option<&str>,
        status: &str,
    ) -> Result<()> {
        let stamp = now();
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        if let Some(app_turn_id) = app_turn_id {
            sqlx::query("UPDATE turns SET status=?,completed_at=? WHERE thread_id=? AND app_server_turn_id=?")
                .bind(status).bind(&stamp).bind(thread_id).bind(app_turn_id).execute(&mut *tx).await?;
        } else {
            sqlx::query("UPDATE turns SET status=?,completed_at=? WHERE id=(SELECT id FROM turns WHERE thread_id=? ORDER BY ordinal DESC LIMIT 1)")
                .bind(status).bind(&stamp).bind(thread_id).execute(&mut *tx).await?;
        }
        sqlx::query("UPDATE threads SET status='idle',last_activity_at=?,updated_at=? WHERE id=?")
            .bind(&stamp)
            .bind(&stamp)
            .bind(thread_id)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(())
    }
    pub async fn import_app_thread(&self, project_id: &str, thread: &Value) -> Result<String> {
        let app_id = thread
            .get("id")
            .and_then(Value::as_str)
            .ok_or_else(|| anyhow!("App Server thread has no id"))?;
        if let Some(id) = self.local_thread_id(app_id).await? {
            self.update_imported_thread(&id, thread).await?;
            return Ok(id);
        }
        let id = new_id("thr");
        let title = imported_thread_title(thread);
        let stamp = unix_value_to_rfc3339(thread.get("updatedAt")).unwrap_or_else(now);
        let status = value_status(thread.get("status"), "idle");
        sqlx::query("INSERT INTO threads(id,project_id,app_server_thread_id,title,status,last_activity_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)")
            .bind(&id).bind(project_id).bind(app_id).bind(title).bind(status).bind(&stamp).bind(&stamp).bind(&stamp)
            .execute(&self.pool).await?;
        Ok(id)
    }
    async fn update_imported_thread(&self, id: &str, thread: &Value) -> Result<()> {
        let title = imported_thread_title(thread);
        let stamp = unix_value_to_rfc3339(thread.get("updatedAt")).unwrap_or_else(now);
        let status = value_status(thread.get("status"), "idle");
        sqlx::query(
            "UPDATE threads SET title=?,status=?,last_activity_at=?,updated_at=? WHERE id=?",
        )
        .bind(title)
        .bind(status)
        .bind(&stamp)
        .bind(&stamp)
        .bind(id)
        .execute(&self.pool)
        .await?;
        Ok(())
    }
    pub async fn import_app_history(&self, thread_id: &str, thread: &Value) -> Result<()> {
        for (turn_index, turn) in thread
            .get("turns")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .enumerate()
        {
            // Commit per turn: a whole-thread transaction can hold the WAL write lock
            // for seconds on large histories and starve interactive writes.
            let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
            let app_turn = turn
                .get("id")
                .and_then(Value::as_str)
                .ok_or_else(|| anyhow!("App Server turn has no id"))?;
            let turn_id = if let Some(id) = sqlx::query_scalar::<_, String>(
                "SELECT id FROM turns WHERE thread_id=? AND app_server_turn_id=?",
            )
            .bind(thread_id)
            .bind(app_turn)
            .fetch_optional(&mut *tx)
            .await?
            {
                id
            } else {
                new_id("trn")
            };
            let status = value_status(turn.get("status"), "completed");
            let started = unix_value_to_rfc3339(turn.get("startedAt"));
            let completed = unix_value_to_rfc3339(turn.get("completedAt"));
            sqlx::query("INSERT INTO turns(id,thread_id,app_server_turn_id,ordinal,status,started_at,completed_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET ordinal=excluded.ordinal,status=excluded.status,started_at=COALESCE(excluded.started_at,turns.started_at),completed_at=COALESCE(excluded.completed_at,turns.completed_at)")
                .bind(&turn_id).bind(thread_id).bind(app_turn).bind(turn_index as i64+1).bind(status).bind(&started).bind(&completed).execute(&mut *tx).await?;
            for item in turn
                .get("items")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                let app_item = item.get("id").and_then(Value::as_str).unwrap_or("");
                let raw_kind = item
                    .get("type")
                    .and_then(Value::as_str)
                    .unwrap_or("unknown");
                let kind = normalize_item_kind(raw_kind);
                let mut existing = if app_item.is_empty() {
                    None
                } else {
                    sqlx::query_scalar::<_, String>(
                        "SELECT id FROM items WHERE turn_id=? AND app_server_item_id=?",
                    )
                    .bind(&turn_id)
                    .bind(app_item)
                    .fetch_optional(&mut *tx)
                    .await?
                };
                if existing.is_none() && kind == "user_message" {
                    existing = sqlx::query_scalar::<_, String>("SELECT id FROM items WHERE turn_id=? AND kind='user_message' AND app_server_item_id IS NULL ORDER BY ordinal LIMIT 1")
                        .bind(&turn_id).fetch_optional(&mut *tx).await?;
                }
                let text = app_item_text(item);
                if existing.is_none()
                    && let Some(content) = text.as_deref().filter(|t| !t.is_empty())
                {
                    // The live path records the same message under the notification's item id,
                    // which does not always match the id the history endpoint returns; fall back
                    // to a content match so backfill never duplicates a recorded message.
                    existing = sqlx::query_scalar::<_, String>(
                        "SELECT id FROM items WHERE turn_id=? AND kind=? AND content_text=? ORDER BY ordinal LIMIT 1",
                    )
                    .bind(&turn_id)
                    .bind(kind)
                    .bind(content)
                    .fetch_optional(&mut *tx)
                    .await?;
                }
                let item_id = existing.unwrap_or_else(|| new_id("itm"));
                let stamp = started.clone().unwrap_or_else(now);
                // New rows take the next free ordinal instead of the app-side index: live-recorded
                // items (user/agent messages) already occupy ordinals, and the (turn_id, ordinal)
                // unique index must never abort the whole history import. Existing rows keep their
                // ordinal so re-imports cannot reshuffle what the live path already persisted.
                sqlx::query("INSERT INTO items(id,turn_id,app_server_item_id,ordinal,kind,status,revision,content_text,structured_detail,occurred_at,completed_at) VALUES(?,?,NULLIF(?,''),COALESCE((SELECT MAX(ordinal)+1 FROM items WHERE turn_id=?),1),?,'completed',1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET app_server_item_id=COALESCE(excluded.app_server_item_id,items.app_server_item_id),kind=excluded.kind,content_text=excluded.content_text,structured_detail=excluded.structured_detail,completed_at=COALESCE(excluded.completed_at,items.completed_at),revision=CASE WHEN items.app_server_item_id IS NOT COALESCE(excluded.app_server_item_id,items.app_server_item_id) OR items.kind IS NOT excluded.kind OR items.content_text IS NOT excluded.content_text OR items.structured_detail IS NOT excluded.structured_detail OR (excluded.completed_at IS NOT NULL AND items.completed_at IS NOT excluded.completed_at) THEN items.revision+1 ELSE items.revision END")
                    .bind(&item_id).bind(&turn_id).bind(app_item).bind(&turn_id).bind(kind).bind(text).bind(serde_json::to_string(item)?).bind(&stamp).bind(&completed).execute(&mut *tx).await?;
            }
            tx.commit().await?;
        }
        sqlx::query("UPDATE threads SET updated_at=? WHERE id=?")
            .bind(now())
            .bind(thread_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn history_records(
        &self,
        thread_id: &str,
        device_id: &str,
    ) -> Result<Vec<HistoryRecord>> {
        let mut records = Vec::new();
        if let Some(thread) = self.thread(thread_id, device_id).await? {
            records.push(HistoryRecord {
                thread: Some(thread),
                turn: None,
                item: None,
            });
        }
        let turns = sqlx::query("SELECT * FROM turns WHERE thread_id=? ORDER BY ordinal")
            .bind(thread_id)
            .fetch_all(&self.pool)
            .await?;
        for row in turns {
            let turn = HistoryTurnView {
                id: row.get("id"),
                thread_id: row.get("thread_id"),
                ordinal: row.get("ordinal"),
                status: row.get("status"),
                started_at: row.get("started_at"),
                completed_at: row.get("completed_at"),
            };
            let turn_id = turn.id.clone();
            records.push(HistoryRecord {
                thread: None,
                turn: Some(turn),
                item: None,
            });
            let items = sqlx::query("SELECT * FROM items WHERE turn_id=? ORDER BY ordinal")
                .bind(&turn_id)
                .fetch_all(&self.pool)
                .await?;
            for item in items {
                let (content_text, content_truncated) = item
                    .get::<Option<String>, _>("content_text")
                    .map(|value| truncate_utf8(value, 256 * 1024))
                    .map(|(value, truncated)| (Some(value), truncated))
                    .unwrap_or((None, false));
                let mut detail = item
                    .get::<Option<String>, _>("structured_detail")
                    .and_then(|value| serde_json::from_str::<Value>(&value).ok());
                let detail_truncated = detail
                    .as_ref()
                    .and_then(|value| serde_json::to_vec(value).ok())
                    .is_some_and(|value| value.len() > 256 * 1024);
                if detail_truncated {
                    detail = Some(serde_json::json!({"truncated":true}));
                }
                records.push(HistoryRecord {
                    thread: None,
                    turn: None,
                    item: Some(HistoryItemView {
                        id: item.get("id"),
                        turn_id: item.get("turn_id"),
                        ordinal: item.get("ordinal"),
                        kind: item.get("kind"),
                        status: item.get("status"),
                        revision: item.get("revision"),
                        content_text,
                        structured_detail: detail,
                        is_truncated: content_truncated || detail_truncated,
                        occurred_at: item.get("occurred_at"),
                        completed_at: item.get("completed_at"),
                    }),
                });
            }
        }
        Ok(records)
    }

    pub async fn receive_command(
        &self,
        queue_epoch: &str,
        sequence: i64,
        target_key: &str,
        priority: i64,
        command: &DeviceCommand,
    ) -> Result<InboxRecord> {
        let json = serde_json::to_string(command)?;
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("INSERT OR IGNORE INTO command_inbox(command_id,queue_epoch,server_sequence,target_key,priority,payload,status,received_at) VALUES(?,?,?,?,?,?,'accepted',?)")
            .bind(&command.command_id).bind(queue_epoch).bind(sequence).bind(target_key).bind(priority).bind(&json).bind(now()).execute(&mut *tx).await?;
        let row = sqlx::query("SELECT * FROM command_inbox WHERE command_id=?")
            .bind(&command.command_id)
            .fetch_optional(&mut *tx)
            .await?;
        let Some(row) = row else {
            let collision: Option<String> = sqlx::query_scalar(
                "SELECT command_id FROM command_inbox WHERE queue_epoch=? AND server_sequence=?",
            )
            .bind(queue_epoch)
            .bind(sequence)
            .fetch_optional(&mut *tx)
            .await?;
            anyhow::bail!(
                "command queue identity collision: epoch={queue_epoch} sequence={sequence} existing={}",
                collision.unwrap_or_else(|| "missing".into())
            );
        };
        if row.get::<String, _>("queue_epoch") != queue_epoch
            || row.get::<i64, _>("server_sequence") != sequence
            || row.get::<String, _>("payload") != json
        {
            anyhow::bail!("command id reused with different queue identity or payload")
        }
        let record = inbox_from_row(&row)?;
        tx.commit().await?;
        Ok(record)
    }

    pub async fn enqueue_local_command(
        &self,
        target_key: &str,
        priority: i64,
        command: &DeviceCommand,
    ) -> Result<InboxRecord> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let sequence: i64 = sqlx::query_scalar("INSERT INTO runtime_state(key,value,updated_at) VALUES('next_local_command_sequence','2',?) ON CONFLICT(key) DO UPDATE SET value=CAST(runtime_state.value AS INTEGER)+1,updated_at=excluded.updated_at RETURNING CAST(value AS INTEGER)-1")
            .bind(now()).fetch_one(&mut *tx).await?;
        let json = serde_json::to_string(command)?;
        sqlx::query("INSERT INTO command_inbox(command_id,queue_epoch,server_sequence,target_key,priority,payload,status,received_at) VALUES(?,'local',?,?,?,?, 'accepted',?)")
            .bind(&command.command_id).bind(sequence).bind(target_key).bind(priority).bind(json).bind(now()).execute(&mut *tx).await?;
        let row = sqlx::query("SELECT * FROM command_inbox WHERE command_id=?")
            .bind(&command.command_id)
            .fetch_one(&mut *tx)
            .await?;
        let record = inbox_from_row(&row)?;
        tx.commit().await?;
        Ok(record)
    }

    pub async fn pending_inbox(&self, limit: i64) -> Result<Vec<InboxRecord>> {
        let rows = sqlx::query("SELECT * FROM command_inbox WHERE status='accepted' ORDER BY received_at,command_id LIMIT ?")
            .bind(limit).fetch_all(&self.pool).await?;
        rows.iter().map(inbox_from_row).collect()
    }
    pub async fn inbox(&self, id: &str) -> Result<Option<InboxRecord>> {
        let row = sqlx::query("SELECT * FROM command_inbox WHERE command_id=?")
            .bind(id)
            .fetch_optional(&self.pool)
            .await?;
        row.as_ref().map(inbox_from_row).transpose()
    }
    pub async fn start_command(&self, id: &str) -> Result<bool> {
        Ok(sqlx::query("UPDATE command_inbox SET status='applying',started_at=? WHERE command_id=? AND status='accepted'").bind(now()).bind(id).execute(&self.pool).await?.rows_affected()==1)
    }
    pub async fn finish_command(
        &self,
        id: &str,
        queue_epoch: &str,
        sequence: i64,
        result: Option<&Value>,
        error: Option<&str>,
        error_message: Option<&str>,
    ) -> Result<()> {
        let status = if error.is_some() {
            "failed"
        } else {
            "completed"
        };
        self.finish_command_as(
            id,
            queue_epoch,
            sequence,
            status,
            result,
            error,
            error_message,
        )
        .await
    }

    pub async fn finish_command_as(
        &self,
        id: &str,
        queue_epoch: &str,
        sequence: i64,
        status: &str,
        result: Option<&Value>,
        error: Option<&str>,
        error_message: Option<&str>,
    ) -> Result<()> {
        if !matches!(status, "completed" | "failed" | "unknown" | "expired") {
            anyhow::bail!("invalid terminal command status")
        }
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("UPDATE command_inbox SET status=?,completed_at=?,result=?,error_code=?,error_message=? WHERE command_id=?").bind(status).bind(now()).bind(result.map(serde_json::to_string).transpose()?).bind(error).bind(error_message).bind(id).execute(&mut *tx).await?;
        if queue_epoch != "local" {
            let key = format!("last_server_sequence:{queue_epoch}");
            sqlx::query("INSERT INTO runtime_state(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=CASE WHEN CAST(value AS INTEGER) < ? THEN excluded.value ELSE value END,updated_at=excluded.updated_at").bind(key).bind(sequence.to_string()).bind(now()).bind(sequence).execute(&mut *tx).await?;
            sqlx::query("INSERT INTO runtime_state(key,value,updated_at) VALUES('active_command_queue_epoch',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(queue_epoch).bind(now()).execute(&mut *tx).await?;
        }
        tx.commit().await?;
        Ok(())
    }

    pub async fn enqueue_event(&self, event: &NuntiusEvent) -> Result<()> {
        sqlx::query("INSERT OR IGNORE INTO event_outbox(event_id,stream_id,sequence,payload,created_at) VALUES(?,?,?,?,?)").bind(&event.event_id).bind(&event.stream_id).bind(event.seq).bind(serde_json::to_string(event)?).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn pending_events(&self, limit: i64) -> Result<Vec<NuntiusEvent>> {
        let rows = sqlx::query("SELECT payload FROM event_outbox ORDER BY created_at LIMIT ?")
            .bind(limit)
            .fetch_all(&self.pool)
            .await?;
        rows.into_iter()
            .map(|r| Ok(serde_json::from_str(&r.get::<String, _>("payload"))?))
            .collect()
    }
    pub async fn ack_event(&self, id: &str) -> Result<()> {
        sqlx::query("DELETE FROM event_outbox WHERE event_id=?")
            .bind(id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }
    pub async fn next_stream_sequence(&self, stream: &str) -> Result<i64> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        sqlx::query("INSERT OR IGNORE INTO stream_sequences(stream_id,next_sequence) VALUES(?,1)")
            .bind(stream)
            .execute(&mut *tx)
            .await?;
        let seq: i64 =
            sqlx::query_scalar("SELECT next_sequence FROM stream_sequences WHERE stream_id=?")
                .bind(stream)
                .fetch_one(&mut *tx)
                .await?;
        sqlx::query("UPDATE stream_sequences SET next_sequence=next_sequence+1 WHERE stream_id=?")
            .bind(stream)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(seq)
    }

    pub async fn enqueue_history(&self, batch: &HistoryBatch) -> Result<()> {
        sqlx::query("INSERT OR IGNORE INTO history_outbox(batch_id,thread_id,to_cursor,payload,created_at) VALUES(?,?,?,?,?)").bind(&batch.batch_id).bind(&batch.thread_id).bind(&batch.to_cursor).bind(serde_json::to_string(batch)?).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn pending_history(&self, limit: i64) -> Result<Vec<HistoryBatch>> {
        let rows = sqlx::query("SELECT payload FROM history_outbox ORDER BY created_at LIMIT ?")
            .bind(limit)
            .fetch_all(&self.pool)
            .await?;
        rows.into_iter()
            .map(|r| Ok(serde_json::from_str(&r.get::<String, _>("payload"))?))
            .collect()
    }
    pub async fn ack_history(&self, batch_id: &str) -> Result<()> {
        sqlx::query("DELETE FROM history_outbox WHERE batch_id=?")
            .bind(batch_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    pub async fn directory_ref_create(&self, path: &Path, ttl_secs: i64) -> Result<String> {
        let id = new_id("dir");
        let expires = OffsetDateTime::now_utc().unix_timestamp() + ttl_secs;
        sqlx::query(
            "INSERT INTO directory_refs(id,canonical_path,expires_at,created_at) VALUES(?,?,?,?)",
        )
        .bind(&id)
        .bind(path.to_string_lossy().as_ref())
        .bind(expires)
        .bind(now())
        .execute(&self.pool)
        .await?;
        Ok(id)
    }
    pub async fn directory_ref_resolve(&self, id: &str) -> Result<Option<PathBuf>> {
        let now = OffsetDateTime::now_utc().unix_timestamp();
        Ok(sqlx::query_scalar::<_, String>(
            "SELECT canonical_path FROM directory_refs WHERE id=? AND expires_at>?",
        )
        .bind(id)
        .bind(now)
        .fetch_optional(&self.pool)
        .await?
        .map(PathBuf::from))
    }
    pub async fn save_app_request(
        &self,
        approval_id: &str,
        request_id: &Value,
        method: &str,
        params: &Value,
    ) -> Result<()> {
        sqlx::query("INSERT OR IGNORE INTO pending_app_requests(approval_id,app_request_id,method,params,status,created_at) VALUES(?,?,?,?,'pending',?)").bind(approval_id).bind(request_id.to_string()).bind(method).bind(serde_json::to_string(params)?).bind(now()).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn claim_app_request(&self, approval_id: &str) -> Result<Option<(Value, String)>> {
        let mut tx = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let claimed = sqlx::query("UPDATE pending_app_requests SET status='responding' WHERE approval_id=? AND status='pending'")
            .bind(approval_id).execute(&mut *tx).await?.rows_affected();
        if claimed != 1 {
            tx.rollback().await?;
            return Ok(None);
        }
        let row = sqlx::query(
            "SELECT app_request_id,method FROM pending_app_requests WHERE approval_id=?",
        )
        .bind(approval_id)
        .fetch_optional(&mut *tx)
        .await?;
        tx.commit().await?;
        row.map(|r| {
            Ok((
                serde_json::from_str(&r.get::<String, _>("app_request_id"))?,
                r.get("method"),
            ))
        })
        .transpose()
    }
    pub async fn finish_app_request(&self, approval_id: &str, status: &str) -> Result<()> {
        if !matches!(status, "decided" | "unknown") {
            anyhow::bail!("invalid approval status")
        }
        sqlx::query("UPDATE pending_app_requests SET status=?,decided_at=? WHERE approval_id=? AND status='responding'").bind(status).bind(now()).bind(approval_id).execute(&self.pool).await?;
        Ok(())
    }
    pub async fn counts(&self) -> Result<(i64, i64, i64, i64)> {
        let projects = sqlx::query_scalar("SELECT COUNT(*) FROM projects WHERE status='active'")
            .fetch_one(&self.pool)
            .await?;
        let inbox = sqlx::query_scalar(
            "SELECT COUNT(*) FROM command_inbox WHERE status IN ('accepted','applying')",
        )
        .fetch_one(&self.pool)
        .await?;
        let outbox = sqlx::query_scalar(
            "SELECT (SELECT COUNT(*) FROM event_outbox)+(SELECT COUNT(*) FROM history_outbox)",
        )
        .fetch_one(&self.pool)
        .await?;
        let active = sqlx::query_scalar("SELECT COUNT(*) FROM threads WHERE status='active'")
            .fetch_one(&self.pool)
            .await?;
        Ok((projects, inbox, outbox, active))
    }
}

fn inbox_from_row(r: &sqlx::sqlite::SqliteRow) -> Result<InboxRecord> {
    Ok(InboxRecord {
        queue_epoch: r.get("queue_epoch"),
        server_sequence: r.get("server_sequence"),
        target_key: r.get("target_key"),
        priority: r.get("priority"),
        command: serde_json::from_str(&r.get::<String, _>("payload"))?,
        status: r.get("status"),
        result: r
            .get::<Option<String>, _>("result")
            .and_then(|value| serde_json::from_str(&value).ok()),
        error_code: r.get("error_code"),
        error_message: r.get("error_message"),
    })
}

fn project_summary(r: &sqlx::sqlite::SqliteRow, device_id: &str) -> ProjectSummary {
    let path = PathBuf::from(r.get::<String, _>("canonical_path"));
    ProjectSummary {
        id: r.get("id"),
        device_id: device_id.into(),
        kind: if r.get::<String, _>("kind") == "system_unassigned" {
            ProjectKind::SystemUnassigned
        } else {
            ProjectKind::Workspace
        },
        display_name: r.get("display_name"),
        path_hint: path.file_name().map(|v| v.to_string_lossy().into_owned()),
        status: r.get("status"),
        repo_name: None,
        branch: None,
        is_dirty: None,
        thread_count: r.get("thread_count"),
        last_activity_at: Some(r.get("updated_at")),
    }
}
fn thread_summary(r: &sqlx::sqlite::SqliteRow, device_id: &str) -> ThreadSummary {
    ThreadSummary {
        id: r.get("id"),
        device_id: device_id.into(),
        project_id: r.get("project_id"),
        app_server_thread_id: r.get("app_server_thread_id"),
        title: r.get("title"),
        status: r.get("status"),
        archived: r.get("archived"),
        history_completeness: HistoryCompleteness::Complete,
        last_synced_at: None,
        last_activity_at: r.get("last_activity_at"),
    }
}

fn imported_thread_title(thread: &Value) -> &str {
    thread
        .get("name")
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .or_else(|| {
            thread
                .get("preview")
                .and_then(Value::as_str)
                .filter(|value| !value.is_empty())
        })
        .unwrap_or("历史对话")
}

fn value_status(value: Option<&Value>, fallback: &str) -> String {
    value
        .and_then(|value| {
            value
                .as_str()
                .or_else(|| value.get("type").and_then(Value::as_str))
        })
        .unwrap_or(fallback)
        .to_string()
}

fn unix_value_to_rfc3339(value: Option<&Value>) -> Option<String> {
    let seconds = value?.as_i64()?;
    OffsetDateTime::from_unix_timestamp(seconds)
        .ok()?
        .format(&time::format_description::well_known::Rfc3339)
        .ok()
}

fn app_item_text(item: &Value) -> Option<String> {
    if let Some(text) = item.get("text").and_then(Value::as_str) {
        return Some(text.into());
    }
    let content = item.get("content")?.as_array()?;
    let parts = content
        .iter()
        .filter_map(|part| part.get("text").and_then(Value::as_str))
        .collect::<Vec<_>>();
    (!parts.is_empty()).then(|| parts.join("\n"))
}

fn normalize_item_kind(kind: &str) -> &str {
    match kind {
        "userMessage" => "user_message",
        "agentMessage" => "agent_message",
        "commandExecution" => "command_execution",
        "fileChange" => "file_change",
        other => other,
    }
}

fn truncate_utf8(value: String, max_bytes: usize) -> (String, bool) {
    if value.len() <= max_bytes {
        return (value, false);
    }
    let mut boundary = max_bytes;
    while !value.is_char_boundary(boundary) {
        boundary -= 1;
    }
    (value[..boundary].to_string(), true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[tokio::test]
    async fn durable_inbox_outbox_and_history_round_trip() {
        let temp = tempfile::tempdir().unwrap();
        let workspace = temp.path().join("workspace");
        std::fs::create_dir(&workspace).unwrap();
        let store = ClientStore::open(temp.path()).await.unwrap();
        store
            .create_project("prj_test", "Test", &workspace, &json!({}))
            .await
            .unwrap();
        store
            .create_thread(
                "thr_test",
                "prj_test",
                "app_thread",
                "Thread",
                &json!({"sandbox":"danger-full-access"}),
            )
            .await
            .unwrap();
        assert!(!store.thread_has_turns("thr_test").await.unwrap());
        assert_eq!(
            store.app_server_options("thr_test").await.unwrap(),
            json!({"sandbox":"danger-full-access"})
        );
        store
            .rebind_app_server_thread("thr_test", "app_thread_rebound")
            .await
            .unwrap();
        assert_eq!(
            store
                .thread("thr_test", "dev_test")
                .await
                .unwrap()
                .unwrap()
                .app_server_thread_id
                .as_deref(),
            Some("app_thread_rebound")
        );
        store
            .record_user_turn("thr_test", Some("app_turn"), "hello")
            .await
            .unwrap();
        store
            .record_agent_message(
                "thr_test",
                Some("app_turn"),
                Some("app_item"),
                "world",
                &json!({"type":"agentMessage"}),
            )
            .await
            .unwrap();
        store
            .import_app_history(
                "thr_test",
                &json!({"turns":[{"id":"app_turn","status":"completed","items":[
                    {"id":"app_user","type":"userMessage","content":[{"type":"text","text":"hello"}]},
                    {"id":"app_item","type":"agentMessage","text":"world"}
                ]}]}),
            )
            .await
            .unwrap();
        let history = store.history_records("thr_test", "dev_test").await.unwrap();
        assert!(history.iter().any(|record| record.thread.is_some()));
        assert_eq!(
            history
                .iter()
                .filter(|record| record.item.is_some())
                .count(),
            2
        );
        let revisions_before = history
            .iter()
            .filter_map(|record| record.item.as_ref().map(|item| item.revision))
            .collect::<Vec<_>>();
        store
            .import_app_history(
                "thr_test",
                &json!({"turns":[{"id":"app_turn","status":"completed","items":[
                    {"id":"app_user","type":"userMessage","content":[{"type":"text","text":"hello"}]},
                    {"id":"app_item","type":"agentMessage","text":"world"}
                ]}]}),
            )
            .await
            .unwrap();
        let revisions_after = store
            .history_records("thr_test", "dev_test")
            .await
            .unwrap()
            .into_iter()
            .filter_map(|record| record.item.map(|item| item.revision))
            .collect::<Vec<_>>();
        assert_eq!(revisions_after, revisions_before);

        let command = DeviceCommand {
            command_id: "cmd_test".into(),
            device_id: "dev_test".into(),
            project_id: None,
            thread_id: None,
            issued_at: now(),
            expires_at: now(),
            command: DeviceCommandKind::Refresh,
        };
        assert_eq!(
            store
                .receive_command("epoch_test", 1, "device:dev_test", 2, &command)
                .await
                .unwrap()
                .status,
            "accepted"
        );
        assert!(store.start_command("cmd_test").await.unwrap());
        store
            .finish_command(
                "cmd_test",
                "epoch_test",
                1,
                Some(&json!({"ok":true})),
                None,
                None,
            )
            .await
            .unwrap();
        assert_eq!(
            store
                .receive_command("epoch_test", 1, "device:dev_test", 2, &command)
                .await
                .unwrap()
                .status,
            "completed"
        );
        assert_eq!(
            store
                .last_server_sequence(Some("epoch_test"))
                .await
                .unwrap(),
            1
        );

        let next_epoch = DeviceCommand {
            command_id: "cmd_next_epoch".into(),
            ..command.clone()
        };
        assert_eq!(
            store
                .receive_command("epoch_next", 1, "device:dev_test", 2, &next_epoch)
                .await
                .unwrap()
                .status,
            "accepted"
        );
        let collision = DeviceCommand {
            command_id: "cmd_collision".into(),
            ..command.clone()
        };
        assert!(
            store
                .receive_command("epoch_test", 1, "device:dev_test", 2, &collision)
                .await
                .is_err()
        );
        let local = DeviceCommand {
            command_id: "cmd_local".into(),
            ..command.clone()
        };
        let local_record = store
            .enqueue_local_command("device:dev_test", 2, &local)
            .await
            .unwrap();
        assert_eq!(local_record.queue_epoch, "local");

        let unassigned = store.ensure_unassigned_project("dev_test").await.unwrap();
        assert_eq!(
            store.ensure_unassigned_project("dev_test").await.unwrap(),
            unassigned
        );
        let uncertain = DeviceCommand {
            command_id: "cmd_uncertain".into(),
            device_id: "dev_test".into(),
            project_id: None,
            thread_id: None,
            issued_at: now(),
            expires_at: now(),
            command: DeviceCommandKind::Refresh,
        };
        store
            .receive_command("epoch_test", 2, "device:dev_test", 2, &uncertain)
            .await
            .unwrap();
        assert!(store.start_command("cmd_uncertain").await.unwrap());
        store.recover_process_state().await.unwrap();
        assert_eq!(
            store.inbox("cmd_uncertain").await.unwrap().unwrap().status,
            "unknown"
        );

        store
            .save_app_request(
                "apr_test",
                &json!(42),
                "item/commandExecution/requestApproval",
                &json!({}),
            )
            .await
            .unwrap();
        assert!(store.claim_app_request("apr_test").await.unwrap().is_some());
        assert!(store.claim_app_request("apr_test").await.unwrap().is_none());
        store
            .finish_app_request("apr_test", "decided")
            .await
            .unwrap();

        let event = NuntiusEvent {
            event_id: "evt_test".into(),
            user_id: None,
            device_id: "dev_test".into(),
            project_id: None,
            thread_id: None,
            turn_id: None,
            stream_id: "device:dev_test".into(),
            seq: 1,
            event_type: "test".into(),
            durability: "durable".into(),
            occurred_at: now(),
            payload: json!({}),
        };
        store.enqueue_event(&event).await.unwrap();
        assert_eq!(store.pending_events(10).await.unwrap().len(), 1);
        store.ack_event("evt_test").await.unwrap();
        assert!(store.pending_events(10).await.unwrap().is_empty());
        let backup = temp.path().join("backup.db");
        store.backup(&backup).await.unwrap();
        assert!(backup.is_file());
    }
}
